import {test, expect, _electron as electron} from '@playwright/test'
import {mkdtempSync, writeFileSync, rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join, resolve} from 'node:path'
import {execFileSync} from 'node:child_process'

test('快捷页面复用待办按钮与事实，运行入口只显示运行和结果计时条', async ({page,request}) => {
  const [records] = await (await request.post('/readevent', {data:[[]]})).json()
  if (records.length) await request.post('/writeevent',{data:records.map(record => ({...record,system:{source_id:record.system.source_id,deleted:true}}))})
  const today = new Date().toLocaleDateString('sv-SE')
  const identities = await (await request.post('/writeevent',{data:['结果','运行','待办'].map(text => ({system:{source_id:null,deleted:false},user:{event:`桌面${text}`},meta:[{kind:'业务区域',text},...(text === '结果' ? [{kind:'属性',text:`日期:${today}`}] : [])]}))})).json()
  await request.post('/writetimer',{data:{key:String(identities[0].source_id),state:'running'}})
  await request.post('/writeevent',{data:['运行','待办'].map(text => ({system:{source_id:null,deleted:false},user:{event:`组内${text}`},meta:[{kind:'业务区域',text},{kind:'闭环',text:'闭环#abcdefabcdefabcdefabcdefabcdefab|桌面闭环'}]}))})
  await page.goto('/?presentation=running')
  await expect(page.locator('#message')).toHaveText('已读取')
  await expect(page.locator('[data-timer-source]')).toHaveCount(1)
  await expect(page.locator('.event-body')).toHaveText(['桌面运行','组内运行'])
  await expect(page.locator('.loop')).toHaveCount(1)
  await expect(page.locator('.result-page,.small-page')).toHaveCount(0)
  await page.goto('/?presentation=todo')
  for (const name of ['新增待办','选择或管理模板','新增闭环']) await expect(page.getByRole('button',{name,exact:true})).toBeVisible()
  await expect(page.locator('.event-body')).toHaveText(['桌面待办','组内待办'])
  await expect(page.getByRole('button',{name:'在闭环下新增待办',exact:true})).toBeVisible()
  await page.locator('.event').filter({hasText:'桌面待办'}).getByRole('button',{name:'开始计时',exact:true}).click()
  await expect(page.locator('.event')).toHaveCount(1)
  await page.goto('/?presentation=running')
  await expect(page.locator('.event')).toHaveCount(3)
  await page.setViewportSize({width:390,height:700})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/desktop-running.png'})
})

test('真实 Electron：设置按键录入、注册与持久化、关闭隐藏、受限桥接', async ({baseURL}) => {
  const directory = mkdtempSync(join(tmpdir(),'compound-electron-'))
  writeFileSync(join(directory,'shortcuts.json'),JSON.stringify({running:'Control+Shift+Alt+F10',todo:'Control+Shift+Alt+F11'}),'utf8')
  const app = await electron.launch({args:[resolve('desktop/main/index.cjs')],env:{...process.env,COMPOUND_DESKTOP_URL:baseURL,COMPOUND_DESKTOP_DATA:directory}})
  try {
    const page = await app.firstWindow(), errors=[]; page.on('pageerror',error => errors.push(error.message))
    await expect(page.locator('#message')).toHaveText('已读取')
    await expect(page.getByRole('button',{name:'快捷键设置'})).toBeVisible()
    expect(await page.evaluate(() => typeof window.require)).toBe('undefined')
    expect(await app.evaluate(({globalShortcut}) => globalShortcut.isRegistered('Control+Shift+Alt+F10'))).toBe(true)
    await page.getByRole('button',{name:'快捷键设置'}).click()
    const setting = page.locator('.shortcut-setting').first().getByRole('button')
    await setting.click(); await setting.press('Control+Shift+Alt+F9')
    await expect(setting).toHaveText('Control+Alt+Shift+F9')
    await page.getByRole('button',{name:'保存快捷键'}).click(); await expect(page.locator('dialog')).toHaveCount(0)
    expect(await app.evaluate(({globalShortcut}) => globalShortcut.isRegistered('Control+Alt+Shift+F9'))).toBe(true)
    expect((await page.evaluate(() => window.compoundDesktop.readSettings())).shortcuts.running).toBe('Control+Alt+Shift+F9')
    await page.getByRole('button',{name:'快捷键设置'}).click()
    await page.locator('.shortcut-setting').last().getByRole('button').click()
    await page.locator('.shortcut-setting').last().getByRole('button').press('Control+Shift+Alt+F9')
    await page.getByRole('button',{name:'保存快捷键'}).click()
    await expect(page.locator('.dialog-error')).toContainText('相同快捷键')
    await page.getByRole('button',{name:'关闭',exact:true}).click()
    await page.screenshot({path:'test-results/electron-dev.png'})
    await app.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].close())
    expect(await app.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].isVisible())).toBe(false)
    const press = keys => execFileSync('powershell.exe',['-NoProfile','-Command',`$keyboard = New-Object -ComObject WScript.Shell; $keyboard.SendKeys('${keys}')`],{windowsHide:true})
    press('^+%{F9}')
    await expect.poll(() => app.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].isVisible())).toBe(true)
    press('^+%{F9}')
    await expect.poll(() => app.evaluate(({BrowserWindow}) => BrowserWindow.getAllWindows()[0].isVisible())).toBe(false)
    press('^+%{F11}')
    await expect(page).toHaveURL(/presentation=todo/)
    await expect(page.getByRole('button',{name:'新增待办',exact:true})).toBeVisible()
    press('^+%{F9}')
    await expect(page).toHaveURL(/presentation=running/)
    expect(errors).toEqual([])
  } finally {await app.close(); rmSync(directory,{recursive:true,force:true})}
})
