import {test, expect} from '@playwright/test'

test.use({baseURL:`http://127.0.0.1:${process.env.COMPOUND_TEST_MOBILE_PORT || 19934}`,viewport:{width:390,height:844},isMobile:true,hasTouch:true})
test('手机公网前缀登录、闭环录入、计时归档、结果与会话隔离', async ({page,request}) => {
  const errors = [], posts = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', value => {if(value.method()==='POST') posts.push(new URL(value.url()).pathname)})
  expect((await request.post('/compound/dev/readevent',{data:[[]]})).status()).toBe(401)
  expect((await request.get('/compound/dev/speech/config')).status()).toBe(401)
  await page.goto('/compound/dev/?presentation=mobile')
  await page.getByLabel('登录密码').fill('wrong')
  await page.getByRole('button',{name:'登录',exact:true}).click()
  await expect(page.getByRole('alert')).toHaveText('密码不正确')
  await page.getByLabel('登录密码').fill('mobile-test-password')
  await page.getByRole('button',{name:'登录',exact:true}).click()
  await expect(page.locator('#message')).toHaveText('已读取')
  await expect(page.getByRole('button',{name:'新增待办',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'选择或管理模板',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'新增闭环',exact:true}).click()
  await page.getByRole('textbox',{name:'闭环名称',exact:true}).fill('手机闭环')
  await page.getByRole('button',{name:'确定',exact:true}).click()
  const loop = page.locator('.loop').filter({hasText:'手机闭环'})
  await loop.getByRole('button',{name:'在闭环下新增待办',exact:true}).click()
  await page.getByLabel('小事正文',{exact:true}).fill('手机读一章')
  await page.getByRole('button',{name:'保存',exact:true}).click()
  await expect(page.locator('.event-body')).toHaveText('手机读一章')
  await page.locator('.event').getByRole('button',{name:'开始计时',exact:true}).click()
  await expect(page.locator('.event')).toHaveCount(0)
  await page.getByRole('navigation',{name:'手机分区'}).getByRole('button',{name:'运行',exact:true}).click()
  await expect(page.locator('.event')).toHaveCount(1)
  await page.locator('.event').getByRole('button',{name:'暂停',exact:true}).click()
  await page.locator('.event').getByRole('button',{name:'继续',exact:true}).click()
  await page.locator('.event').getByRole('button',{name:'归档',exact:true}).click()
  await page.getByRole('button',{name:'4 · 挺好',exact:true}).click()
  await page.getByRole('navigation',{name:'手机分区'}).getByRole('button',{name:'归档',exact:true}).click()
  await expect(page.locator('.event-body')).toHaveText('手机读一章')
  await expect(page.locator('.event-stats')).toContainText('4分')
  await page.getByRole('navigation',{name:'手机分区'}).getByRole('button',{name:'结果',exact:true}).click()
  await page.getByRole('button',{name:'新增根事项',exact:true}).click()
  await page.getByRole('textbox',{name:'复利事项名称',exact:true}).fill('手机阅读')
  await page.getByRole('button',{name:'确定',exact:true}).click()
  const itemTitle=page.locator('.item[data-item="手机阅读"] > .group-head')
  await expect(itemTitle).toBeVisible()
  expect(await itemTitle.evaluate(node=>getComputedStyle(node).minHeight)).toBe('24px')
  expect(await itemTitle.locator('button').first().evaluate(node=>getComputedStyle(node).minHeight)).toBe('28px')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/mobile-390.png',fullPage:true})
  await page.reload(); await expect(page.locator('#message')).toHaveText('已读取')
  await page.getByRole('button',{name:'退出登录',exact:true}).click()
  await expect(page.getByLabel('登录密码')).toBeVisible()
  expect(errors).toEqual([])
  expect(posts.every(path => path.startsWith('/compound/dev/'))).toBe(true)
})
