import {test, expect} from '@playwright/test'

const panel = (page, name = '') => page.locator('.small-page').filter({has: page.locator(`:scope > .slice-heading > h2`, {hasText: new RegExp(`^${name || '小事'}$`)})})
const area = (host, name = '待办') => host.locator(`.area[data-area="${name}"]`)
const card = (host, text) => host.locator('.event').filter({has: host.page().locator('.event-body', {hasText: text})})
const dialog = page => page.locator('dialog[open]').last()
const today = () => new Date().toLocaleDateString('sv-SE')
const tag = name => ({kind:'区域切片',text:name})
const loopTag = (name = '训练闭环', id = 'a') => ({kind:'闭环',text:`闭环#${id.repeat(32)}|${name}`})
const read = async request => (await (await request.post('/readevent',{data:[[]]})).json())[0]
const slices = async request => (await (await request.post('/readslice',{data:null})).json())
async function seed(request, text, slice = null, region = '待办', extra = []) {
  const response = await request.post('/writeevent',{data:[{system:{source_id:null,deleted:false},user:{event:text},meta:[{kind:'业务区域',text:region},...(!extra.some(value => value.kind === '属性' && value.text.startsWith('日期:')) ? [{kind:'属性',text:`日期:${today()}`}] : []),...(slice ? [tag(slice)] : []),...extra]}]})
  expect(response.ok()).toBe(true)
  return (await response.json())[0].source_id
}
async function open(page) {await page.goto('/'); await expect(page.locator('#message')).toHaveText('已读取')}
async function named(page, button, name) {
  await button.click(); await dialog(page).locator('input').fill(name); await dialog(page).getByRole('button',{name:'确定',exact:true}).click()
  await expect(page.locator('#message')).toHaveText('已保存'); await expect(page.locator('dialog')).toHaveCount(0)
}
async function record(page, button, text) {
  await button.click(); await page.getByLabel('小事正文',{exact:true}).fill(text); await dialog(page).getByRole('button',{name:'保存',exact:true}).click()
  await expect(page.locator('#message')).toHaveText('已保存'); await expect(page.locator('dialog')).toHaveCount(0)
}
async function drag(page, source, target, accepted = true, position = 'inside') {
  await source.scrollIntoViewIfNeeded(); await target.scrollIntoViewIfNeeded()
  const a = await source.boundingBox(), b = await target.boundingBox()
  await page.mouse.move(a.x + Math.min(80,a.width / 2),a.y + a.height / 2); await page.mouse.down()
  await page.mouse.move(a.x + Math.min(80,a.width / 2) + 12,a.y + a.height / 2,{steps:5})
  const y = b.y + (position === 'before' ? 2 : position === 'after' ? b.height - 2 : b.height / 2)
  await page.mouse.move(b.x + Math.min(65,b.width / 2),y,{steps:15}); await page.mouse.move(b.x + Math.min(65,b.width / 2) + 1,y)
  if (accepted) await expect(target).toHaveClass(new RegExp(`drop-${position}`))
  else await expect(page.locator('.drop-inside,.drop-before,.drop-after')).toHaveCount(0)
  await page.mouse.up()
  if (accepted) await expect(page.locator('#message')).toHaveText('已保存')
}
let errors, writes
test.beforeEach(async ({page,request}) => {
  errors = []; writes = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => {const path = new URL(request.url()).pathname; if(path.startsWith('/write')) writes.push(path)})
  const all = await read(request)
  if (all.length) await request.post('/writeevent',{data:all.map(event => ({system:{source_id:event.system.source_id,deleted:true},user:event.user,meta:event.meta}))})
  await request.post('/writeslice',{data:[]})
  await request.post('/writeforest',{data:{workspace:{item_template_id:null,forest:['结果','待办','运行','归档'].map(text => ({tag:{kind:'业务区域',text},is_fold:false,children:[]}))}}})
})
test.afterEach(async ({request}) => {
  expect(errors).toEqual([])
  await request.post('/writeslice',{data:[]})
})

test('空切片管理、插入顺序、名称校验和持久化', async ({page,request}) => {
  await open(page)
  await expect(panel(page).getByRole('button',{name:'修改切片',exact:true})).toHaveCount(0)
  await expect(panel(page).getByRole('button',{name:'删除切片',exact:true})).toHaveCount(0)
  await named(page,panel(page).getByRole('button',{name:'新增切片',exact:true}),'训练')
  await named(page,panel(page,'训练').getByRole('button',{name:'新增切片',exact:true}),'福利')
  await named(page,panel(page).getByRole('button',{name:'新增切片',exact:true}),'临时')
  expect(await slices(request)).toEqual(['临时','训练','福利'])
  await page.reload(); await expect(page.locator('.slice-heading h2')).toHaveText(['小事','临时','训练','福利'])
  for (const name of ['临时','训练','福利']) await expect(panel(page,name).locator('.area')).toHaveCount(3)
  await panel(page,'训练').getByRole('button',{name:'修改切片',exact:true}).click()
  await dialog(page).locator('input').fill('福利'); await dialog(page).getByRole('button',{name:'确定',exact:true}).click()
  await expect(dialog(page).locator('.dialog-error')).toContainText('重复')
  await dialog(page).locator('input').fill('小事'); await dialog(page).getByRole('button',{name:'确定',exact:true}).click()
  await expect(dialog(page).locator('.dialog-error')).toContainText('小事')
  await dialog(page).getByRole('button',{name:'关闭',exact:true}).click()
  expect(writes.every(path => path === '/writeslice')).toBe(true)
})

test('改名删除覆盖全部状态与日期，两个写入阶段失败均可明确重试', async ({page,request}) => {
  await request.post('/writeslice',{data:['训练','福利']})
  const ids = []
  for (const region of ['待办','运行','归档','结果']) ids.push(await seed(request,region,'训练',region))
  await seed(request,'旧日期','训练','归档',[{kind:'属性',text:'备注:保留'}])
  const all = await read(request), old = all.find(event => event.user.event === '旧日期')
  await request.post('/writeevent',{data:[{system:{source_id:old.system.source_id,deleted:false},user:old.user,meta:old.meta.map(value => value.text.startsWith('日期:') ? {...value,text:'日期:2000-01-01'} : value)}]})
  await open(page)
  await page.route('**/writeevent',route => route.fulfill({status:400,json:{error:'标签保存失败'}}))
  await panel(page,'训练').getByRole('button',{name:'修改切片',exact:true}).click(); await dialog(page).locator('input').fill('训练新名'); await dialog(page).getByRole('button',{name:'确定',exact:true}).click()
  await expect(dialog(page).locator('.dialog-error')).toContainText('标签保存失败'); expect(await slices(request)).toEqual(['训练','福利'])
  await page.unroute('**/writeevent')
  await page.route('**/writeslice',route => route.fulfill({status:400,json:{error:'列表保存失败'}}))
  await dialog(page).getByRole('button',{name:'确定',exact:true}).click()
  await expect(dialog(page).locator('.dialog-error')).toContainText('小事已更新，切片列表保存失败')
  expect((await read(request)).every(event => event.meta.some(value => value.kind === '区域切片' && value.text === '训练新名'))).toBe(true)
  await page.unroute('**/writeslice'); await dialog(page).getByRole('button',{name:'确定',exact:true}).click()
  await expect(panel(page,'训练新名')).toBeVisible(); await expect(page.locator('dialog')).toHaveCount(0)
  await panel(page,'训练新名').getByRole('button',{name:'删除切片',exact:true}).click(); await dialog(page).getByRole('button',{name:'确定',exact:true}).click()
  await expect(page.locator('dialog')).toHaveCount(0); expect(await slices(request)).toEqual(['福利'])
  const after = await read(request)
  expect(after).toHaveLength(5); expect(after.every(event => !event.meta.some(value => value.kind === '区域切片'))).toBe(true)
  expect(ids.every(id => after.some(event => event.system.source_id === id))).toBe(true)
  expect(writes).not.toContain('/writeforest')
})

test('真实拖拽切换小事和闭环切片，保留状态、标签、timer，跨状态拒绝', async ({page,request}) => {
  await request.post('/writeslice',{data:['训练','福利']})
  const loop = loopTag(), id = await seed(request,'运行成员','训练','运行',[loop,{kind:'属性',text:'耗时:3s'},{kind:'属性',text:'评分:4'}])
  await request.post('/writetimer',{data:{key:String(id),state:'running'}})
  await seed(request,'待办甲','训练','待办',[loop]); await seed(request,'待办乙','训练','待办',[loop]); await seed(request,'福利同组','福利','待办',[loop])
  await seed(request,'归档同组','训练','归档',[loop])
  await seed(request,'目标运行组','训练','运行',[loopTag('另一组','b')])
  await open(page); const before = await read(request)
  await drag(page,card(panel(page,'训练'),'运行成员'),area(panel(page,'福利'),'待办'),false)
  await drag(page,card(panel(page,'训练'),'运行成员'),panel(page,'福利').locator('.slice-heading h2'))
  const changed = (await read(request)).find(event => event.system.source_id === id)
  expect(changed.meta.filter(value => value.kind !== '区域切片')).toEqual(before.find(event => event.system.source_id === id).meta.filter(value => value.kind !== '区域切片'))
  const [timer] = await (await request.post('/readtimer',{data:[String(id)]})).json(); expect(timer.state).toBe('running')
  await drag(page,area(panel(page,'训练')).locator('.loop > .group-head'),panel(page,'福利').locator('.slice-heading h2'))
  await expect(area(panel(page,'福利')).locator('.loop .count')).toHaveText('3 件')
  await expect(area(panel(page,'福利')).locator('.loop .event')).toHaveCount(3)
  await expect(area(panel(page,'训练'),'归档').locator('.loop .event')).toHaveCount(1)
  await drag(page,card(panel(page,'福利'),'运行成员'),panel(page).locator('.slice-heading h2'))
  await expect(card(panel(page),'运行成员')).toBeVisible()
  expect((await read(request)).find(event => event.system.source_id === id).meta.some(value => value.kind === '区域切片')).toBe(false)
  await drag(page,card(panel(page),'运行成员'),area(panel(page,'训练'),'运行').locator('.loop > .group-head'))
  const final = (await read(request)).find(event => event.system.source_id === id)
  expect(final.meta).toContainEqual(tag('训练')); expect(final.meta).toContainEqual(loop)
  expect(writes.every(path => path === '/writeevent')).toBe(true)
})

test('切片新增待办、闭环首条及取消、快速运行、模板实例化', async ({page,request}) => {
  await request.post('/writeslice',{data:['训练']}); await open(page)
  await record(page,area(panel(page,'训练')).getByRole('button',{name:'新增待办',exact:true}),'切片待办')
  await area(panel(page,'训练')).getByRole('button',{name:'新增闭环',exact:true}).click(); await dialog(page).locator('input').fill('取消的闭环'); await dialog(page).getByRole('button',{name:'确定',exact:true}).click()
  await dialog(page).getByRole('button',{name:'关闭',exact:true}).click(); await expect(panel(page,'训练').locator('.loop')).toHaveCount(0)
  await area(panel(page,'训练')).getByRole('button',{name:'新增闭环',exact:true}).click(); await dialog(page).locator('input').fill('新闭环'); await dialog(page).getByRole('button',{name:'确定',exact:true}).click()
  await page.getByLabel('小事正文',{exact:true}).fill('首条'); await dialog(page).getByRole('button',{name:'保存',exact:true}).click(); await expect(panel(page,'训练').locator('.loop')).toHaveCount(1)
  await record(page,panel(page,'训练').getByRole('button',{name:'在闭环下新增待办',exact:true}),'组内新增')
  await record(page,area(panel(page,'训练'),'运行').getByRole('button',{name:'快速运行',exact:true}),'快速切片')
  const template = [{system:{version_id:null,source_id:null,deleted:false},user:{event:'模板小事'},meta:[{kind:'闭环',text:'切片模板'}]}]
  await request.post('/writelooptemplate',{data:[{id:null,deleted:false,events:template}]})
  await area(panel(page,'训练')).getByRole('button',{name:'选择或管理模板',exact:true}).click(); await dialog(page).getByRole('button',{name:'切片模板 · 1 条',exact:true}).last().click()
  await expect(card(panel(page,'训练'),'模板小事')).toBeVisible()
  expect((await read(request)).every(event => event.meta.some(value => value.kind === '区域切片' && value.text === '训练'))).toBe(true)
  expect(writes).not.toContain('/writeforest')
  await page.screenshot({path:'test-results/slices-content.png'})
})

test('闭环删除只影响当前切片全部日期成员，森林节点为其他切片保留', async ({page,request}) => {
  await request.post('/writeslice',{data:['训练','福利']}); const loop = loopTag()
  await request.post('/writeforest',{data:{workspace:{item_template_id:null,forest:['结果','待办','运行','归档'].map(text => ({tag:{kind:'业务区域',text},children:text === '待办' ? [{tag:loop,is_fold:false,children:[]}] : []}))}}})
  await seed(request,'训练甲','训练','待办',[loop]); await seed(request,'福利甲','福利','待办',[loop]); await seed(request,'训练运行','训练','运行',[loop])
  await seed(request,'训练旧日期','训练','待办',[loop,{kind:'属性',text:'日期:2000-01-01'}])
  await open(page)
  await panel(page,'训练').getByRole('button',{name:'删除闭环组',exact:true}).click(); await dialog(page).getByRole('button',{name:'确定',exact:true}).click(); await expect(page.locator('dialog')).toHaveCount(0)
  const after = await read(request); expect(after.map(event => event.user.event).sort()).toEqual(['福利甲','训练运行'])
  const forest = (await (await request.post('/readforest',{data:{workspace:true}})).json()).workspace.forest
  expect(forest.find(node => node.tag.text === '待办').children).toHaveLength(1)
  expect(writes).not.toContain('/writeforest')
})

test('普通状态切换保留切片，归档日期范围共享且重新统计分组', async ({page,request}) => {
  await request.post('/writeslice',{data:['训练','福利']})
  const loop = loopTag(), id = await seed(request,'状态流','训练','待办',[loop])
  await seed(request,'今日训练','训练','归档',[loop,{kind:'属性',text:'耗时:3s'}])
  await seed(request,'历史训练','训练','归档',[loop,{kind:'属性',text:'日期:2000-01-01'},{kind:'属性',text:'耗时:7s'}])
  await seed(request,'历史福利','福利','归档',[loop,{kind:'属性',text:'日期:2000-01-01'}])
  await open(page)
  await card(panel(page,'训练'),'状态流').getByRole('button',{name:'开始计时',exact:true}).click()
  await expect(card(area(panel(page,'训练'),'运行'),'状态流')).toBeVisible()
  await card(panel(page,'训练'),'状态流').getByRole('button',{name:'返回待办',exact:true}).click()
  await expect(card(area(panel(page,'训练'),'待办'),'状态流')).toBeVisible()
  await card(panel(page,'训练'),'状态流').getByRole('button',{name:'开始计时',exact:true}).click()
  await card(panel(page,'训练'),'状态流').getByRole('button',{name:'归档',exact:true}).click()
  await dialog(page).getByRole('button',{name:'不评分，完成',exact:true}).click(); await expect(page.locator('dialog')).toHaveCount(0)
  const saved = (await read(request)).find(event => event.system.source_id === id)
  expect(saved.meta).toContainEqual(tag('训练')); expect(saved.meta).toContainEqual({kind:'业务区域',text:'归档'})
  await expect(area(panel(page,'训练'),'归档').locator('.loop .count')).toHaveText('2 件')
  await expect(card(panel(page,'训练'),'历史训练')).toHaveCount(0)
  await panel(page,'训练').getByLabel('归档日期范围').selectOption('all')
  await expect(panel(page,'福利').getByLabel('归档日期范围')).toHaveValue('all')
  await expect(area(panel(page,'训练'),'归档').locator('.loop .count')).toHaveText('3 件')
  await expect(area(panel(page,'福利'),'归档').locator('.loop .count')).toHaveText('1 件')
  const timers = await (await request.post('/readtimer',{data:[String(id)]})).json()
  expect(timers[0]).toMatchObject({state:'paused',elapsed_ms:0})
  expect(writes).not.toContain('/writeforest')
})

test('共用折叠与完整顺序，同切片排序不覆盖其他切片闭环', async ({page,request}) => {
  await request.post('/writeslice',{data:['训练','福利']})
  await seed(request,'甲训练','训练','待办',[loopTag('甲','a')]); await seed(request,'甲福利','福利','待办',[loopTag('甲','a')]); await seed(request,'乙训练','训练','待办',[loopTag('乙','b')]); await seed(request,'丙福利','福利','待办',[loopTag('丙','c')])
  await open(page)
  const heads = area(panel(page,'训练')).locator('.loop > .group-head')
  await heads.filter({hasText:'甲'}).locator('.loop-name').click()
  await expect(card(panel(page,'训练'),'甲训练')).not.toBeVisible(); await expect(card(panel(page,'福利'),'甲福利')).not.toBeVisible()
  await drag(page,heads.filter({hasText:'乙'}),heads.filter({hasText:'甲'}),true,'before')
  const forest = (await (await request.post('/readforest',{data:{workspace:true}})).json()).workspace.forest
  expect(forest.find(node => node.tag.text === '待办').children.map(node => node.tag.text)).toHaveLength(3)
  expect(writes.every(path => path === '/writeforest')).toBe(true)
})

test('缺失名称提示、重新归位、宽屏换行与手机快捷入口全集', async ({page,request}) => {
  await seed(request,'待办训练','恢复切片'); await seed(request,'运行训练','恢复切片','运行')
  await open(page); await expect(panel(page).locator('.slice-warning')).toContainText('恢复切片'); await expect(card(panel(page),'待办训练')).toBeVisible()
  await named(page,panel(page).getByRole('button',{name:'新增切片',exact:true}),'恢复切片')
  await expect(panel(page).locator('.slice-warning')).toHaveCount(0); await expect(card(panel(page,'恢复切片'),'待办训练')).toBeVisible()
  await named(page,panel(page,'恢复切片').getByRole('button',{name:'新增切片',exact:true}),'空切片')
  await page.screenshot({path:'test-results/slices-wide.png'})
  const boxes = await page.locator('.small-page').evaluateAll(nodes => nodes.map(node => ({x:node.getBoundingClientRect().x,y:node.getBoundingClientRect().y})))
  expect(boxes[1].x).toBeGreaterThan(boxes[0].x); expect(boxes[2].y).toBeGreaterThan(boxes[0].y)
  await page.setViewportSize({width:1100,height:900}); await page.screenshot({path:'test-results/slices-narrow.png'})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({width:390,height:844}); await expect(page.locator('.slice-panels')).toHaveCount(0); await expect(page.locator('.event-body')).toContainText(['待办训练'])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/slices-mobile.png'})
  await page.goto('/?presentation=todo'); await expect(page.locator('.event-body')).toContainText(['待办训练']); await expect(page.locator('.slice-panels')).toHaveCount(0)
  await page.goto('/?presentation=running'); await expect(page.locator('.event-body')).toContainText(['运行训练'])
  const snapshot = await page.evaluate(() => window.compoundWatch.perform('pause', document.querySelector('.event').dataset.source))
  expect(snapshot.running.direct.map(item => item.title)).toContain('运行训练')
  expect(snapshot.todo.direct.map(item => item.title)).toContain('待办训练')
})
