import {test, expect} from '@playwright/test'
test.skip(process.env.COMPOUND_TEST_SPEECH !== '1', '仅显式启用时调用真实腾讯识别')
test('真实麦克风音轨与腾讯转录，停顿自动确认并保留键盘补充', async ({page, request}, testInfo) => {
  test.setTimeout(90000)
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await page.context().grantPermissions(['microphone'])
  await page.goto('/'); await expect(page.locator('#message')).toHaveText('已读取')
  const config = await (await request.get('/speech/config')).json(); expect(config.configured).toBe(true)
  await page.getByRole('button', {name: '新增待办', exact: true}).click()
  await expect(page.locator('.voice-status')).toContainText('正在听', {timeout: 25000})
  await page.getByLabel('小事正文', {exact: true}).fill('键盘尾部验证')
  await expect(page.getByLabel('语音识别正文')).not.toBeEmpty({timeout: 45000})
  await page.screenshot({path: testInfo.outputPath('speech-desktop.png'), fullPage: true})
  await expect(page.locator('.score-card')).toBeVisible({timeout: 45000})
  const transcript = await page.getByLabel('语音识别正文').textContent()
  expect(transcript.trim().length).toBeGreaterThan(0)
  await page.getByRole('button', {name: '4 · 挺好', exact: true}).click()
  await expect(page.locator('dialog')).toHaveCount(0)
  const [events] = await (await request.post('/readevent', {data: [[]]})).json()
  expect(events).toHaveLength(1)
  expect(events[0].user.event).toBe(transcript + '键盘尾部验证')
  expect(events[0].meta).toContainEqual({kind: '属性', text: '评分:4'})
  expect(errors).toEqual([])
  await page.setViewportSize({width: 390, height: 844})
  await page.getByRole('button', {name: '新增待办', exact: true}).click()
  await page.screenshot({path: testInfo.outputPath('speech-mobile.png'), fullPage: true})
  await page.getByRole('button', {name: '关闭', exact: true}).click()
})
