import {test, expect} from '@playwright/test'
import {datesInRange} from '../../frontend/shell/projection/dates.js'
const area = (page, name) => page.locator(`.area[data-area="${name}"]`)
const item = (page, name) => page.locator(`.item[data-item="${name}"]`)
const card = (page, text) => page.locator('.event').filter({has: page.locator('.event-body', {hasText: text})})
const dialog = page => page.locator('dialog[open]').last()
async function named(page, target, value) {await target.click(); await dialog(page).locator('input').fill(value); await dialog(page).getByRole('button',{name:'确定',exact:true}).click(); await expect(page.locator('#message')).toHaveText('已保存'); await expect(page.locator('dialog')).toHaveCount(0)}
async function confirmed(page, target) {await target.click(); await dialog(page).getByRole('button',{name:'确定',exact:true}).click(); await expect(page.locator('#message')).toHaveText('已保存'); await expect(page.locator('dialog')).toHaveCount(0)}
async function record(page, target, text, attributes = '', score = null) {
  if (score) attributes = [attributes,`评分:${score}`].filter(Boolean).join('\n')
  await target.locator('..').hover(); await target.click(); await page.getByLabel('小事正文',{exact:true}).fill(text)
  if (attributes) {await dialog(page).locator('summary').click(); await page.getByLabel('属性标签').fill(attributes)}
  const scoring = (await dialog(page).locator('.capture-steps').innerText()).includes('评分')
  await dialog(page).getByRole('button',{name:'保存',exact:true}).click()
  if (scoring) {if(await dialog(page).locator('.duration-card').isVisible()) await dialog(page).getByRole('button',{name:'不记录耗时',exact:true}).click(); await dialog(page).getByRole('button',{name:score ? `${score} · 挺好` : '不评分，完成',exact:true}).click()}
  await expect(page.locator('#message')).toHaveText('已保存'); await expect(page.locator('dialog')).toHaveCount(0)
}
async function templateRecord(page,text) {
  await dialog(page).getByRole('button',{name:'+ 增加模板事项',exact:true}).click()
  await page.getByLabel('小事正文',{exact:true}).fill(text)
  await expect(dialog(page).locator('.score-card')).not.toBeVisible()
  await dialog(page).getByRole('button',{name:'保存',exact:true}).click()
  await expect(page.getByLabel('小事正文',{exact:true})).toHaveCount(0)
}
const allowed = ['/writeevent','/readevent','/writeforest','/readforest','/writelooptemplate','/readlooptemplate','/writetimer','/readtimer']
const head = target => target.locator(':scope > .group-head')
async function drag(page, source, target, position = 'inside', accepted = true) {
  const a = await source.boundingBox(), b = await target.boundingBox()
  await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2); await page.mouse.down()
  await page.mouse.move(a.x + a.width / 2 + 12, a.y + a.height / 2, {steps:5})
  const y = b.y + (position === 'before' ? 2 : position === 'after' ? b.height - 2 : b.height / 2)
  await page.mouse.move(b.x + Math.min(70,b.width / 2), y, {steps:12})
  await page.mouse.move(b.x + Math.min(70,b.width / 2) + 1, y)
  if (accepted) await expect(target).toHaveClass(new RegExp(`drop-${position}`))
  else await expect(page.locator('.drop-inside,.drop-before,.drop-after')).toHaveCount(0)
  await page.mouse.up()
  if (accepted) await expect(page.locator('#message')).toHaveText('已保存')
}
const currentEvents = async request => (await (await request.post('/readevent',{data:[[]]})).json())[0]
const memory = async request => (await (await request.post('/readforest',{data:{workspace:true,item_templates:null}})).json())
let errors, requests

test.beforeEach(async ({page,request}) => {
  errors=[]; requests=[]; page.on('pageerror',error => errors.push(error.message)); page.on('request',request => {if(request.method()==='POST') requests.push(new URL(request.url()).pathname)})
  await page.addInitScript(() => {for(const name of ['prompt','confirm','alert']) window[name]=() => {throw new Error('禁止原生弹窗')}})
  const [events]=await (await request.post('/readevent',{data:[[]]})).json()
  if(events.length) await request.post('/writeevent',{data:events.map(event => ({system:{source_id:event.system.source_id,deleted:true},user:event.user,meta:event.meta}))})
  const memory=await (await request.post('/readforest',{data:{workspace:true,item_templates:null}})).json()
  await request.post('/writeforest',{data:{workspace:{item_template_id:null,forest:['结果','待办','运行','归档'].map(text => ({tag:{kind:'业务区域',text},children:[]}))},item_templates:memory.item_templates.map(value => ({id:value.id,deleted:true,name:value.name,forest:value.forest}))}})
  const templates=await (await request.post('/readlooptemplate',{data:null})).json()
  if(templates.length) await request.post('/writelooptemplate',{data:templates.map(value => ({id:value.id,deleted:true,events:value.events}))})
  await page.goto('/'); await expect(page.locator('#message')).toHaveText('已读取')
})
test.afterEach(async () => {expect(errors).toEqual([]); expect(requests.every(path => allowed.includes(path))).toBe(true)})

test('待办新增只录正文，编辑属性和软删除',async ({page,request}) => {
  await area(page,'待办').getByRole('button',{name:'新增待办',exact:true}).click()
  await expect(dialog(page).locator('.capture-steps')).toHaveText('1 正文'); await expect(dialog(page).locator('.score-card')).not.toBeVisible()
  await page.getByLabel('小事正文',{exact:true}).fill('读一章'); await dialog(page).locator('summary').click(); await page.getByLabel('属性标签').fill('备注:保留这条属性'); await dialog(page).getByRole('button',{name:'保存',exact:true}).click()
  const [created]=await (await request.post('/readevent',{data:[[]]})).json(); expect(created[0].user.event).toBe('读一章'); expect(created[0].meta.some(tag=>tag.text.startsWith('评分:'))).toBe(false)
  await card(page,'读一章').getByRole('button',{name:'修改事实',exact:true}).click(); await page.getByLabel('小事正文',{exact:true}).fill('读两章'); await dialog(page).locator('summary').click(); await page.getByLabel('属性标签').fill('备注:保留这条属性\n评分:4\n耗时:12.5s'); await dialog(page).getByRole('button',{name:'保存修改',exact:true}).click(); await expect(card(page,'读两章')).toHaveCount(1); const [edited]=await (await request.post('/readevent',{data:[[]]})).json(); expect(edited[0].meta).toEqual(expect.arrayContaining([{kind:'属性',text:'备注:保留这条属性'},{kind:'属性',text:'评分:4'},{kind:'属性',text:'耗时:12.5s'}]))
  await page.getByLabel('搜索',{exact:true}).fill('不存在的内容'); await expect(card(page,'读两章')).not.toBeVisible(); await page.getByLabel('搜索',{exact:true}).fill(''); await expect(card(page,'读两章')).toBeVisible()
  await confirmed(page,card(page,'读两章').getByRole('button',{name:'删除事实',exact:true})); expect((await (await request.post('/readevent',{data:[[]]})).json())[0]).toHaveLength(0)
})

test('开始新计时会暂停旧计时，暂停只影响当前项，刷新和版本变更不换key',async ({page,request}) => {
  await record(page,area(page,'待办').getByRole('button',{name:'新增待办',exact:true}),'计时甲','耗时:2s',4)
  await record(page,area(page,'待办').getByRole('button',{name:'新增待办',exact:true}),'计时乙')
  const id=await card(page,'计时甲').getAttribute('data-source')
  await card(page,'计时甲').getByRole('button',{name:'开始计时',exact:true}).click(); await expect(area(page,'运行').locator('.event')).toHaveCount(1)
  await card(page,'计时乙').getByRole('button',{name:'开始计时',exact:true}).click(); await expect(area(page,'运行').locator('.event')).toHaveCount(2)
  await expect(card(page,'计时甲').getByRole('button',{name:'继续',exact:true})).toBeVisible(); await expect(card(page,'计时乙').getByRole('button',{name:'暂停',exact:true})).toBeVisible()
  const writes=requests.filter(path=>path.startsWith('/write')).length; await expect(card(page,'计时乙').locator('.timer-display')).not.toHaveText('0秒',{timeout:4000}); expect(requests.filter(path=>path.startsWith('/write'))).toHaveLength(writes)
  await card(page,'计时乙').getByRole('button',{name:'暂停',exact:true}).click(); await expect(card(page,'计时甲').getByRole('button',{name:'继续',exact:true})).toBeVisible(); await expect(card(page,'计时乙').getByRole('button',{name:'继续',exact:true})).toBeVisible()
  await page.reload(); await expect(page.locator('#message')).toHaveText('已读取'); await expect(card(page,'计时甲').getByRole('button',{name:'继续',exact:true})).toBeVisible()
  await card(page,'计时乙').getByRole('button',{name:'继续',exact:true}).click(); await expect(card(page,'计时乙').getByRole('button',{name:'暂停',exact:true})).toBeVisible()
  await card(page,'计时甲').getByRole('button',{name:'继续',exact:true}).click(); await expect(card(page,'计时乙').getByRole('button',{name:'继续',exact:true})).toBeVisible()
  await card(page,'计时甲').getByRole('button',{name:'修改事实',exact:true}).click(); await page.getByLabel('小事正文',{exact:true}).fill('计时甲修订'); await dialog(page).getByRole('button',{name:'保存修改',exact:true}).click(); await expect(card(page,'计时甲修订')).toHaveAttribute('data-source',id)
  await card(page,'计时甲修订').getByRole('button',{name:'归档',exact:true}).click(); await dialog(page).getByRole('button',{name:'4 · 挺好',exact:true}).click(); await expect(card(page,'计时甲修订').getByRole('button',{name:'移入运行',exact:true})).toBeVisible(); await expect(card(page,'计时甲修订')).toContainText('4分')
  await card(page,'计时乙').getByRole('button',{name:'继续',exact:true}).click()
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'跨区计时')
  await item(page,'跨区计时').getByRole('button',{name:'开始计时',exact:true}).click(); await expect(card(page,'计时乙').getByRole('button',{name:'继续',exact:true})).toBeVisible()
  await card(page,'计时乙').getByRole('button',{name:'继续',exact:true}).click(); await expect(page.locator('.running-strip').getByRole('button',{name:'继续',exact:true})).toBeVisible()
  await card(page,'计时乙').getByRole('button',{name:'归档',exact:true}).click(); await dialog(page).getByRole('button',{name:'不评分，完成',exact:true}).click(); await expect(area(page,'归档').locator('.event')).toHaveCount(2)
  const [all]=await (await request.post('/readevent',{data:[[]]})).json(); expect(Number(all.find(event => String(event.system.source_id)===id).meta.find(tag => tag.text.startsWith('耗时:')).text.slice(3,-1))).toBeGreaterThan(2)
})

test('两个网页每秒同步计时，保留未保存草稿',async ({page,context,request}) => {
  await record(page,area(page,'待办').getByRole('button',{name:'新增待办',exact:true}),'同步甲')
  await record(page,area(page,'待办').getByRole('button',{name:'新增待办',exact:true}),'同步乙')
  const other=await context.newPage(), otherErrors=[]
  other.on('pageerror',error=>otherErrors.push(error.message))
  await other.goto('/'); await expect(other.locator('#message')).toHaveText('已读取')
  await card(page,'同步甲').getByRole('button',{name:'开始计时',exact:true}).click()
  await expect(card(other,'同步甲').getByRole('button',{name:'暂停',exact:true})).toBeVisible({timeout:4000})
  await area(page,'待办').getByRole('button',{name:'新增待办',exact:true}).click(); await page.getByLabel('小事正文',{exact:true}).fill('未保存草稿')
  await card(other,'同步乙').getByRole('button',{name:'开始计时',exact:true}).click()
  await expect(page.getByLabel('小事正文',{exact:true})).toHaveValue('未保存草稿')
  await dialog(page).getByRole('button',{name:'关闭',exact:true}).click()
  await expect(card(page,'同步甲').getByRole('button',{name:'继续',exact:true})).toBeVisible({timeout:4000})
  await expect(card(page,'同步乙').getByRole('button',{name:'暂停',exact:true})).toBeVisible()
  const frozen=await card(page,'同步甲').locator('.timer-display').innerText()
  await page.waitForTimeout(1200); await expect(card(page,'同步甲').locator('.timer-display')).toHaveText(frozen)
  const ids=await Promise.all(['同步甲','同步乙'].map(name=>card(page,name).getAttribute('data-source')))
  const states=await (await request.post('/readtimer',{data:ids})).json()
  expect(states.map(value=>value.state)).toEqual(['paused','running'])
  expect(otherErrors).toEqual([]); await other.close()
})

test('Watch窄桥复用现有命令运行、暂停、继续与归档',async ({page,request}) => {
  await record(page,area(page,'待办').getByRole('button',{name:'新增待办',exact:true}),'手表交互验收')
  const id=await card(page,'手表交互验收').getAttribute('data-source')
  let snapshot=await page.evaluate(id=>window.compoundWatch.perform('run',id),id)
  expect(snapshot.running.direct.map(item=>item.title)).toContain('手表交互验收')
  await expect(card(page,'手表交互验收').getByRole('button',{name:'暂停',exact:true})).toBeVisible()
  await page.evaluate(id=>window.compoundWatch.perform('pause',id),id)
  await expect(card(page,'手表交互验收').getByRole('button',{name:'继续',exact:true})).toBeVisible()
  await page.evaluate(id=>window.compoundWatch.perform('resume',id),id)
  await expect(card(page,'手表交互验收').locator('.timer-display')).not.toHaveText('0秒',{timeout:4000})
  snapshot=await page.evaluate(id=>window.compoundWatch.perform('archive',id),id)
  expect(snapshot.running.direct.map(item=>item.id)).not.toContain(id)
  await expect(card(page,'手表交互验收').getByRole('button',{name:'移入运行',exact:true})).toBeVisible()
  const [timer]=await (await request.post('/readtimer',{data:[id]})).json()
  expect(timer).toMatchObject({state:'paused',elapsed_ms:0})
  const [saved]=await (await request.post('/readevent',{data:[[]]})).json()
  expect(Number(saved[0].meta.find(tag=>tag.text.startsWith('耗时:')).text.slice(3,-1))).toBeGreaterThan(0)
  await expect(page.evaluate(()=>window.compoundWatch.perform('unknown','1'))).rejects.toThrow('不支持的手表操作')
})

test('嵌套事项、视图隔离、改名与跨区域分支删除',async ({page}) => {
  await named(page,page.getByRole('button',{name:'新增视图',exact:true}),'学习视图'); const view=await page.locator('#view-select').inputValue()
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'学习')
  await named(page,item(page,'学习').locator(':scope > .group-head').getByRole('button',{name:'新增子事项',exact:true}),'阅读')
  await record(page,item(page,'阅读').locator(':scope > .group-head').getByRole('button',{name:'记录一条',exact:true}),'读完一章')
  await item(page,'学习').locator(':scope > .group-head').getByRole('button',{name:'收起',exact:true}).click(); await expect(item(page,'阅读')).not.toBeVisible(); await item(page,'学习').locator(':scope > .group-head').getByRole('button',{name:'展开',exact:true}).click(); await expect(item(page,'阅读')).toBeVisible()
  await named(page,page.getByRole('button',{name:'新增视图',exact:true}),'运动视图'); await expect(item(page,'学习')).toHaveCount(0)
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'运动')
  await page.locator('#view-select').selectOption(view); await expect(item(page,'阅读')).toHaveCount(1); await expect(item(page,'运动')).toHaveCount(0)
  await named(page,item(page,'阅读').locator(':scope > .group-head').getByRole('button',{name:'重命名事项',exact:true}),'精读'); await expect(item(page,'精读').locator('.event')).toHaveCount(1)
  await card(page,'读完一章').getByRole('button',{name:'开始计时',exact:true}).click(); await expect(area(page,'运行').locator('.event')).toHaveCount(0); await expect(area(page,'结果').locator('.event')).toHaveCount(1)
  await page.reload(); await expect(item(page,'精读')).toHaveCount(1)
  await confirmed(page,item(page,'学习').locator(':scope > .group-head').getByRole('button',{name:'删除事项分支',exact:true})); await expect(page.locator('.event')).toHaveCount(0)
})

test('闭环同名隔离、改名、跨区域删除及刷新空节点',async ({page},testInfo) => {
  await named(page,area(page,'待办').getByRole('button',{name:'新增闭环',exact:true}),'每日闭环'); await named(page,area(page,'待办').getByRole('button',{name:'新增闭环',exact:true}),'每日闭环')
  const loops=area(page,'待办').locator('.loop'); await expect(loops).toHaveCount(2); expect(await loops.nth(0).getAttribute('data-loop')).not.toBe(await loops.nth(1).getAttribute('data-loop'))
  await record(page,loops.nth(0).getByRole('button',{name:'在闭环下新增待办',exact:true}),'闭环甲'); await record(page,loops.nth(1).getByRole('button',{name:'在闭环下新增待办',exact:true}),'闭环乙'); await page.screenshot({path:testInfo.outputPath('loops.png'),fullPage:true})
  await named(page,loops.nth(0).getByRole('button',{name:'重命名闭环',exact:true}),'新闭环名'); await card(page,'闭环甲').getByRole('button',{name:'开始计时',exact:true}).click(); await expect(area(page,'运行').locator('.loop')).toHaveCount(1)
  await confirmed(page,area(page,'待办').locator('.loop').filter({hasText:'新闭环名'}).getByRole('button',{name:'删除闭环组',exact:true})); await expect(card(page,'闭环甲')).toHaveCount(0); await expect(card(page,'闭环乙')).toHaveCount(1)
  await named(page,area(page,'待办').getByRole('button',{name:'新增闭环',exact:true}),'空闭环'); await page.reload(); await expect(area(page,'待办')).toContainText('空闭环')
})

test('模板草稿一键保存、编辑、重复实例化及删除',async ({page},testInfo) => {
  await page.getByRole('button',{name:'选择或管理模板',exact:true}).click(); await dialog(page).getByRole('button',{name:'+ 增加模板',exact:true}).click(); await page.getByLabel('模板名称').fill('阅读模板'); await templateRecord(page,'阅读十页'); await templateRecord(page,'写总结')
  const writes=requests.filter(path => path==='/writelooptemplate').length; expect(writes).toBe(0)
  await dialog(page).getByRole('button',{name:'保存模板',exact:true}).click(); await expect(page.getByLabel('模板名称')).toHaveValue('阅读模板')
  await dialog(page).getByRole('button',{name:'重命名模板',exact:true}).click(); await page.getByLabel('模板名称').fill('精读模板'); await dialog(page).getByRole('button',{name:'修改模板事项',exact:true}).last().click(); await page.getByLabel('模板小事正文').last().fill('写一句总结'); await dialog(page).getByRole('button',{name:'保存模板',exact:true}).click(); await expect(page.getByLabel('模板名称')).toHaveValue('精读模板')
  await templateRecord(page,'临时草稿'); await dialog(page).getByRole('button',{name:'删除模板事项',exact:true}).last().click(); await expect(page.getByLabel('模板小事正文')).toHaveCount(2)
  await dialog(page).getByRole('button',{name:'关闭',exact:true}).click(); await page.reload(); await expect(page.locator('#message')).toHaveText('已读取'); await page.getByRole('button',{name:'选择或管理模板',exact:true}).click(); await expect(page.getByLabel('模板名称')).toHaveValue('精读模板')
  await page.screenshot({path:testInfo.outputPath('template.png'),fullPage:true})
  await dialog(page).getByRole('button',{name:'精读模板 · 2 条',exact:true}).click(); await expect(area(page,'待办').locator('.event')).toHaveCount(2)
  await page.getByRole('button',{name:'选择或管理模板',exact:true}).click(); await dialog(page).getByRole('button',{name:'精读模板 · 2 条',exact:true}).click(); await expect(area(page,'待办').locator('.loop')).toHaveCount(2)
  await page.getByRole('button',{name:'选择或管理模板',exact:true}).click(); await dialog(page).getByRole('button',{name:'删除模板',exact:true}).click(); await dialog(page).getByRole('button',{name:'确定',exact:true}).click(); await expect(page.locator('.template-draft')).toHaveCount(0); await expect(area(page,'待办').locator('.event')).toHaveCount(4)
})

test('写失败保留输入，结束失败保留暂停耗时并可重试',async ({page,request}) => {
  await page.getByRole('button',{name:'新增待办',exact:true}).click(); await page.getByLabel('小事正文',{exact:true}).fill('失败输入')
  await page.route('**/writeevent',route => route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'测试写入失败'})})); await dialog(page).getByRole('button',{name:'保存',exact:true}).click(); await expect(page.locator('#message')).toHaveText('测试写入失败'); await expect(page.getByLabel('小事正文',{exact:true})).toHaveValue('失败输入'); await expect(page.locator('.event')).toHaveCount(0)
  await page.unroute('**/writeevent'); await dialog(page).getByRole('button',{name:'保存',exact:true}).click(); await expect(card(page,'失败输入')).toHaveCount(1)
  await card(page,'失败输入').getByRole('button',{name:'开始计时',exact:true}).click(); await expect(card(page,'失败输入').locator('.timer-display')).not.toHaveText('0秒',{timeout:4000}); const id=await card(page,'失败输入').getAttribute('data-source')
  await page.route('**/writeevent',route => route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'测试写入失败'})})); await card(page,'失败输入').getByRole('button',{name:'归档',exact:true}).click(); await dialog(page).getByRole('button',{name:'不评分，完成',exact:true}).click(); await expect(page.locator('#message')).toHaveText('测试写入失败'); await expect(card(page,'失败输入').getByRole('button',{name:'继续',exact:true})).toBeVisible()
  const [timer]=await (await request.post('/readtimer',{data:[id]})).json(); expect(timer.state).toBe('paused'); expect(timer.elapsed_ms).toBeGreaterThan(0)
  await page.unroute('**/writeevent'); await dialog(page).getByRole('button',{name:'不评分，完成',exact:true}).click(); await expect(card(page,'失败输入').getByRole('button',{name:'移入运行',exact:true})).toBeVisible()
})

test('结果直接计时、结束统一录入覆盖，空正文不显示且左右完全隔离',async ({page,request},testInfo) => {
  const consoleErrors=[]; page.on('console',message => {if(message.type()==='error') consoleErrors.push(message.text())})
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'长期积累')
  const forestBefore=await (await request.post('/readforest',{data:{workspace:true,item_templates:null}})).json(), startIndex=requests.length
  await item(page,'长期积累').getByRole('button',{name:'开始计时',exact:true}).click()
  await expect(page.locator('dialog')).toHaveCount(0); await expect(page.locator('.running-strip>div')).toHaveCount(1); await expect(page.locator('.event')).toHaveCount(0)
  const [initial]=await (await request.post('/readevent',{data:[[]]})).json(); expect(initial[0].user.event).toBe(''); expect(initial[0].meta).toEqual(expect.arrayContaining([{kind:'业务区域',text:'结果'},{kind:'属性',text:'耗时:0s'}])); expect(initial[0].meta.some(tag=>tag.text.startsWith('评分:'))).toBe(false)
  const source=initial[0].system.source_id
  await expect(page.locator('.running-strip .timer-display')).not.toHaveText('0秒',{timeout:4000})
  await page.locator('.running-strip').getByRole('button',{name:'结束',exact:true}).click(); await expect(page.getByLabel('小事正文',{exact:true})).toHaveValue('')
  await page.getByLabel('小事正文',{exact:true}).fill('完成阅读'); await dialog(page).getByRole('button',{name:'保存',exact:true}).click(); await dialog(page).getByRole('button',{name:'4 · 挺好',exact:true}).click()
  await expect(card(page,'完成阅读')).toHaveAttribute('data-source',String(source)); await expect(page.locator('.running-strip')).not.toBeVisible(); await expect(area(page,'运行').locator('.event')).toHaveCount(0)
  let [saved]=await (await request.post('/readevent',{data:[[]]})).json(); const previous=Number(saved[0].meta.find(tag=>tag.text.startsWith('耗时:')).text.slice(3,-1)); expect(previous).toBeGreaterThan(0)
  await card(page,'完成阅读').getByRole('button',{name:'开始计时',exact:true}).click(); await page.locator('.running-strip').getByRole('button',{name:'暂停',exact:true}).click(); await expect(page.locator('.running-strip')).toContainText('已暂停')
  await page.locator('.running-strip').getByRole('button',{name:'继续',exact:true}).click(); await expect(page.locator('.running-strip')).toContainText('计时中')
  await page.locator('.running-strip').getByRole('button',{name:'结束',exact:true}).click(); await expect(page.getByLabel('小事正文',{exact:true})).toHaveValue('完成阅读'); await page.getByLabel('小事正文',{exact:true}).fill('完成阅读和笔记'); await dialog(page).getByRole('button',{name:'保存',exact:true}).click(); await dialog(page).getByRole('button',{name:'不评分，完成',exact:true}).click()
  await expect(card(page,'完成阅读和笔记')).toHaveCount(1); [saved]=await (await request.post('/readevent',{data:[[]]})).json(); expect(saved[0].system.source_id).toBe(source); expect(saved[0].meta.some(tag=>tag.text.startsWith('评分:'))).toBe(false); expect(Number(saved[0].meta.find(tag=>tag.text.startsWith('耗时:')).text.slice(3,-1))).toBeGreaterThanOrEqual(previous)
  expect(requests.slice(startIndex)).not.toContain('/writeforest'); expect(await (await request.post('/readforest',{data:{workspace:true,item_templates:null}})).json()).toEqual(forestBefore)
  await page.screenshot({path:testInfo.outputPath('desktop.png'),fullPage:true}); await page.setViewportSize({width:390,height:844}); await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true); await page.screenshot({path:testInfo.outputPath('mobile.png'),fullPage:true}); expect(consoleErrors).toEqual([])
})

test('结果记录耗时快捷卡片与自定义，保存后选择评分',async ({page,request}) => {
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'练习')
  await item(page,'练习').locator(':scope > .group-head').hover(); await item(page,'练习').getByRole('button',{name:'记录一条',exact:true}).click(); await page.getByLabel('小事正文',{exact:true}).fill('练习三分钟'); await dialog(page).getByRole('button',{name:'保存',exact:true}).click(); await dialog(page).getByRole('button',{name:'3 分钟',exact:true}).click(); await dialog(page).getByRole('button',{name:'4 · 挺好',exact:true}).click(); await expect(card(page,'练习三分钟')).toHaveCount(1)
  await item(page,'练习').locator(':scope > .group-head').hover(); await item(page,'练习').getByRole('button',{name:'记录一条',exact:true}).click(); await page.getByLabel('小事正文',{exact:true}).fill('练习自定义'); await dialog(page).getByRole('button',{name:'保存',exact:true}).click(); await dialog(page).getByRole('button',{name:'自定义',exact:true}).click(); await page.getByLabel('自定义耗时（分钟）').fill('2.5'); await dialog(page).getByRole('button',{name:'确认耗时',exact:true}).click(); await dialog(page).getByRole('button',{name:'不评分，完成',exact:true}).click(); await expect(card(page,'练习自定义')).toHaveCount(1)
  const [all]=await (await request.post('/readevent',{data:[[]]})).json(); expect(all.find(event=>event.user.event==='练习三分钟').meta).toEqual(expect.arrayContaining([{kind:'属性',text:'耗时:180s'},{kind:'属性',text:'评分:4'}])); expect(all.find(event=>event.user.event==='练习自定义').meta).toContainEqual({kind:'属性',text:'耗时:150s'})
})

test('返回待办只改event，右侧带事项标签也不进入结果计时条',async ({page,request}) => {
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'同名事项')
  const created=await (await request.post('/writeevent',{data:[{system:{source_id:null,deleted:false},user:{event:'右边独立事实'},meta:[{kind:'业务区域',text:'待办'},{kind:'复利事项',text:'同名事项'},{kind:'属性',text:'耗时:300s'}]}]})).json(); const id=created[0].source_id
  await page.reload(); await expect(page.locator('#message')).toHaveText('已读取'); const before=requests.length
  await area(page,'结果').getByRole('button',{name:'投入回顾',exact:true}).click(); await expect(dialog(page)).not.toContainText('右边独立事实'); await expect(dialog(page)).toContainText('0 条小事'); await dialog(page).getByRole('button',{name:'关闭',exact:true}).click()
  await card(page,'右边独立事实').getByRole('button',{name:'开始计时',exact:true}).click(); await expect(card(page,'右边独立事实').getByRole('button',{name:'暂停',exact:true})).toBeVisible(); await expect(page.locator('.running-strip')).not.toBeVisible()
  await card(page,'右边独立事实').getByRole('button',{name:'返回待办',exact:true}).click(); await expect(area(page,'待办').locator('.event')).toHaveCount(1); await expect(card(page,'右边独立事实').locator('.timer-display')).toHaveCount(0); await expect(card(page,'右边独立事实').getByRole('button',{name:'开始计时',exact:true})).toHaveCount(1)
  const [timer]=await (await request.post('/readtimer',{data:[String(id)]})).json(); expect(timer.state).toBe('running'); expect(requests.slice(before)).not.toContain('/writeforest')
})

test('结果计时切换与暂停，空正文结束失败保留输入与耗时',async ({page,request}) => {
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'独立计时')
  await item(page,'独立计时').getByRole('button',{name:'开始计时',exact:true}).click(); await expect(page.locator('.running-strip>div')).toHaveCount(1)
  await item(page,'独立计时').getByRole('button',{name:'开始计时',exact:true}).click(); const strips=page.locator('.running-strip>div'); await expect(strips).toHaveCount(2)
  await expect(strips.nth(0)).toContainText('计时中'); await expect(strips.nth(1)).toContainText('已暂停')
  await strips.nth(0).getByRole('button',{name:'暂停',exact:true}).click(); await expect(strips.nth(0)).toContainText('已暂停'); await expect(strips.nth(1)).toContainText('已暂停')
  await strips.nth(0).getByRole('button',{name:'继续',exact:true}).click(); await expect(strips.nth(0)).toContainText('计时中'); await expect(strips.nth(1)).toContainText('已暂停')
  await page.reload(); await expect(page.locator('#message')).toHaveText('已读取'); await expect(strips).toHaveCount(2)
  const [before]=await (await request.post('/readevent',{data:[[]]})).json(); const id=String(before[0].system.source_id)
  await strips.nth(0).getByRole('button',{name:'结束',exact:true}).click(); await expect(page.getByLabel('小事正文',{exact:true})).toHaveValue(''); await dialog(page).getByRole('button',{name:'保存',exact:true}).click()
  await page.route('**/writeevent',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'结果保存失败'})})); await dialog(page).getByRole('button',{name:'不评分，完成',exact:true}).click(); await expect(page.locator('#message')).toHaveText('结果保存失败'); await expect(page.getByLabel('小事正文',{exact:true})).toHaveValue('')
  const [paused]=await (await request.post('/readtimer',{data:[id]})).json(); expect(paused.state).toBe('paused'); const [unchanged]=await (await request.post('/readevent',{data:[[]]})).json(); expect(unchanged).toEqual(before)
  await page.unroute('**/writeevent'); await dialog(page).getByRole('button',{name:'不评分，完成',exact:true}).click(); await expect(strips).toHaveCount(1); await expect(page.locator('.event')).toHaveCount(0); const [reset]=await (await request.post('/readtimer',{data:[id]})).json(); expect(reset.elapsed_ms).toBe(0); expect(reset.state).toBe('paused')
})

test('共用事实条与文件夹闭环，图标无框、标题折叠与窄屏',async ({page},testInfo) => {
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'组件示例')
  await record(page,item(page,'组件示例').getByRole('button',{name:'记录一条',exact:true}),'结果事实','备注:属性保留',4)
  await named(page,area(page,'待办').getByRole('button',{name:'新增闭环',exact:true}),'日常练习')
  await record(page,area(page,'待办').locator('.loop').getByRole('button',{name:'在闭环下新增待办',exact:true}),'练习事实','耗时:12s',4)
  const loop=area(page,'待办').locator('.loop'), head=loop.locator(':scope > .group-head'), count=requests.length
  await expect(head.locator('svg')).toHaveCount(3); await expect(head).toHaveAttribute('aria-expanded','true')
  await head.locator('.loop-name').click(); await expect(head).toHaveAttribute('aria-expanded','false'); await expect(card(page,'练习事实')).not.toBeVisible(); expect(requests.slice(count)).toContain('/writeforest'); expect(requests.slice(count)).not.toContain('/writeevent'); expect(requests.slice(count)).not.toContain('/writetimer')
  await head.focus(); await head.press('Enter'); await expect(head).toHaveAttribute('aria-expanded','true'); await expect(card(page,'练习事实')).toBeVisible()
  await card(page,'练习事实').getByRole('button',{name:'开始计时',exact:true}).click(); await expect(area(page,'运行').locator('.event')).toHaveCount(1); await expect(area(page,'运行').locator('.loop .group-head svg')).toHaveCount(0)
  const hue=await loop.evaluate(node=>node.style.getPropertyValue('--loop-hue')); expect(await area(page,'运行').locator('.loop').evaluate(node=>node.style.getPropertyValue('--loop-hue'))).toBe(hue)
  await page.reload(); await expect(page.locator('#message')).toHaveText('已读取'); expect(await area(page,'运行').locator('.loop').evaluate(node=>node.style.getPropertyValue('--loop-hue'))).toBe(hue)
  expect(await card(page,'练习事实').locator('button').evaluateAll(buttons=>buttons.map(button=>button.dataset.slot))).toEqual(['play','archive','todo','edit','delete'])
  await expect(card(page,'练习事实').locator('.event-stats')).toHaveText('12秒 · 4分'); await expect(card(page,'结果事实').getByRole('button',{name:'评分',exact:true})).toHaveCount(0); await expect(card(page,'结果事实').getByRole('button',{name:'修改耗时',exact:true})).toHaveCount(0)
  await page.getByRole('heading',{name:'小事',exact:true}).hover(); expect(await page.locator('.event button,.loop-tab button,.small-page .stage-title button').evaluateAll(buttons=>buttons.every(button=>getComputedStyle(button).borderTopWidth==='0px' && getComputedStyle(button).backgroundColor==='rgba(0, 0, 0, 0)'))).toBe(true)
  expect(await card(page,'结果事实').evaluate(row=>{const css=getComputedStyle(row); return Number.parseFloat(css.paddingTop)/Number.parseFloat(css.fontSize)})).toBe(.3)
  await page.screenshot({path:testInfo.outputPath('components-desktop.png'),fullPage:true}); await page.setViewportSize({width:390,height:844}); await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true); await page.screenshot({path:testInfo.outputPath('components-mobile.png'),fullPage:true})
  await page.getByRole('navigation',{name:'手机分区'}).getByRole('button',{name:'运行',exact:true}).click()
  await card(page,'练习事实').getByRole('button',{name:'归档',exact:true}).click(); await dialog(page).getByRole('button',{name:'不评分，完成',exact:true}).click()
  await page.getByRole('navigation',{name:'手机分区'}).getByRole('button',{name:'归档',exact:true}).click()
  await expect(area(page,'归档').locator('.event')).toHaveCount(1); await expect(area(page,'归档').locator('.loop .group-head svg')).toHaveCount(0)
  await page.getByRole('navigation',{name:'手机分区'}).getByRole('button',{name:'待办',exact:true}).click()
  await page.getByRole('button',{name:'选择或管理模板',exact:true}).click(); await dialog(page).getByRole('button',{name:'+ 增加模板',exact:true}).click(); await page.getByLabel('模板名称').fill('复用组件'); await templateRecord(page,'模板事实'); await dialog(page).getByRole('button',{name:'修改模板事项',exact:true}).click()
  await expect(dialog(page).locator('.loop')).toHaveCount(1); await expect(dialog(page).locator('.event .event-body')).toHaveText('模板事实'); await expect(dialog(page).locator('.event button')).toHaveCount(2)
  const templateHead=dialog(page).locator('.loop > .group-head'); await templateHead.locator('.loop-name').click(); await expect(templateHead).toHaveAttribute('aria-expanded','false'); await templateHead.focus(); await templateHead.press('Space'); await expect(templateHead).toHaveAttribute('aria-expanded','true'); await page.screenshot({path:testInfo.outputPath('components-template-mobile.png'),fullPage:true})
})

test('录入三卡片、取消与快速运行，归档评分覆盖及耗时累加',async ({page,request},testInfo) => {
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'录入示例')
  const head=item(page,'录入示例').locator(':scope > .group-head'); expect(await head.locator('.branch-actions button').evaluateAll(buttons=>buttons.map(button=>button.getAttribute('aria-label')))).toEqual(['开始计时','记录一条'])
  await head.hover(); await head.getByRole('button',{name:'记录一条',exact:true}).click(); await page.getByLabel('小事正文',{exact:true}).fill('尚未保存'); await dialog(page).getByRole('button',{name:'关闭',exact:true}).click(); expect((await (await request.post('/readevent',{data:[[]]})).json())[0]).toHaveLength(0)
  await head.hover(); await head.getByRole('button',{name:'记录一条',exact:true}).click(); await page.getByLabel('小事正文',{exact:true}).fill('三个卡片顺序录入')
  await expect(dialog(page).locator('.capture-card:visible')).toHaveCount(1); await page.screenshot({path:testInfo.outputPath('capture-text.png'),fullPage:true})
  await dialog(page).getByRole('button',{name:'保存',exact:true}).click(); await expect(dialog(page).locator('.duration-card')).toBeVisible(); await expect(dialog(page).locator('.text-card')).not.toBeVisible(); await page.screenshot({path:testInfo.outputPath('capture-duration.png'),fullPage:true})
  await dialog(page).getByRole('button',{name:'5 分钟',exact:true}).click(); await expect(dialog(page).locator('.score-card')).toBeVisible(); await page.screenshot({path:testInfo.outputPath('capture-score.png'),fullPage:true}); await dialog(page).getByRole('button',{name:'3 · 一般',exact:true}).click(); await expect(card(page,'三个卡片顺序录入')).toContainText('5分0秒 · 3分')
  const before=requests.length
  await area(page,'运行').getByRole('button',{name:'快速运行',exact:true}).click(); await expect(dialog(page).locator('.text-card')).toBeVisible(); await page.getByLabel('小事正文',{exact:true}).fill('快速运行事实'); await dialog(page).getByRole('button',{name:'保存',exact:true}).click(); await expect(area(page,'运行').locator('.event')).toHaveCount(1); await expect(card(page,'快速运行事实').locator('.event-stats')).not.toBeVisible()
  await expect(card(page,'快速运行事实').locator('.timer-display')).not.toHaveText('0秒',{timeout:4000}); const id=await card(page,'快速运行事实').getAttribute('data-source'), [old]=await (await request.post('/readevent',{data:[[]]})).json()
  await card(page,'快速运行事实').getByRole('button',{name:'归档',exact:true}).click(); await expect(dialog(page).locator('.score-card')).toBeVisible(); await expect(dialog(page).locator('.text-card')).not.toBeVisible(); await dialog(page).getByRole('button',{name:'关闭',exact:true}).click(); const [unchanged]=await (await request.post('/readevent',{data:[[]]})).json(); expect(unchanged).toEqual(old); await expect(card(page,'快速运行事实').getByRole('button',{name:'继续',exact:true})).toBeVisible()
  await card(page,'快速运行事实').getByRole('button',{name:'归档',exact:true}).click(); await dialog(page).getByRole('button',{name:'4 · 挺好',exact:true}).click(); await expect(area(page,'归档').locator('.event')).toHaveCount(1)
  const [archived]=await (await request.post('/readevent',{data:[[]]})).json(); const first=archived.find(event=>String(event.system.source_id)===id); expect(first.meta).toContainEqual({kind:'属性',text:'评分:4'}); const seconds=Number(first.meta.find(tag=>tag.text.startsWith('耗时:')).text.slice(3,-1)); expect(seconds).toBeGreaterThan(0)
  await card(page,'快速运行事实').getByRole('button',{name:'移入运行',exact:true}).click(); await expect(area(page,'运行').locator('.event')).toHaveCount(1); await card(page,'快速运行事实').getByRole('button',{name:'归档',exact:true}).click(); await dialog(page).getByRole('button',{name:'不评分，完成',exact:true}).click(); await expect(area(page,'归档').locator('.event')).toHaveCount(1)
  const [saved]=await (await request.post('/readevent',{data:[[]]})).json(); const last=saved.find(event=>String(event.system.source_id)===id); expect(last.meta.some(tag=>tag.text.startsWith('评分:'))).toBe(false); expect(Number(last.meta.find(tag=>tag.text.startsWith('耗时:')).text.slice(3,-1))).toBeGreaterThanOrEqual(seconds); expect(requests.slice(before)).not.toContain('/writeforest')
  await page.setViewportSize({width:390,height:844}); await page.getByRole('navigation',{name:'手机分区'}).getByRole('button',{name:'结果',exact:true}).click(); await head.hover(); await head.getByRole('button',{name:'记录一条',exact:true}).click(); await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true); await page.screenshot({path:testInfo.outputPath('capture-mobile.png'),fullPage:true}); await dialog(page).getByRole('button',{name:'保存',exact:true}).click(); await page.screenshot({path:testInfo.outputPath('duration-mobile.png'),fullPage:true}); await dialog(page).getByRole('button',{name:'1 分钟',exact:true}).click(); await page.screenshot({path:testInfo.outputPath('score-mobile.png'),fullPage:true})
})

test('真实拖拽事项子树与兄弟顺序，迁移全部成员并同步视图',async ({page,request}) => {
  await named(page,page.getByRole('button',{name:'新增视图',exact:true}),'拖拽视图')
  for(const name of ['甲','乙','空']) await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),name)
  await named(page,head(item(page,'甲')).getByRole('button',{name:'新增子事项',exact:true}),'子')
  await record(page,head(item(page,'子')).getByRole('button',{name:'记录一条',exact:true}),'子树事实','备注:保留',4)
  const original=(await currentEvents(request))[0]
  await drag(page,head(item(page,'甲')),head(item(page,'乙')))
  await expect(item(page,'乙').locator('.item[data-item="甲"]')).toHaveCount(1)
  let saved=(await currentEvents(request))[0]
  expect(saved.system.source_id).toBe(original.system.source_id)
  expect(saved.meta).toEqual(expect.arrayContaining([{kind:'复利事项',text:'乙'},{kind:'复利事项',text:'甲'},{kind:'复利事项',text:'子'},{kind:'属性',text:'备注:保留'}]))
  let state=await memory(request); expect(state.item_templates.find(x=>x.id===state.workspace.item_template_id).forest[0].children[0].tag.text).toBe('甲')
  await drag(page,head(item(page,'甲')),head(item(page,'空')),'before')
  saved=(await currentEvents(request))[0]; expect(saved.meta.some(x=>x.text==='乙')).toBe(false)
  const version=saved.system.version_id
  await drag(page,head(item(page,'甲')),head(item(page,'空')),'after')
  expect((await currentEvents(request))[0].system.version_id).toBeGreaterThan(version)
  expect((await memory(request)).workspace.forest[0].children.map(x=>x.tag.text)).toEqual(['乙','空','甲'])
  const writes=requests.length
  await drag(page,head(item(page,'甲')),head(item(page,'子')),'inside',false)
  expect(requests.slice(writes).filter(x=>x.startsWith('/write'))).toEqual([])
  const beforeEmpty=requests.length
  await drag(page,head(item(page,'空')),head(item(page,'乙')))
  expect(requests.slice(beforeEmpty)).toContain('/writeforest'); expect(requests.slice(beforeEmpty)).not.toContain('/writeevent')
  await page.reload(); await expect(item(page,'乙').locator('.item[data-item="空"]')).toHaveCount(1)
})

test('真实拖拽事实只写标签，闭环排序只写森林，拒绝跨区域',async ({page,request},testInfo) => {
  for(const name of ['左','右']) await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),name)
  await record(page,head(item(page,'左')).getByRole('button',{name:'记录一条',exact:true}),'结果拖拽')
  let start=requests.length
  await drag(page,card(page,'结果拖拽'),head(item(page,'右')))
  expect(requests.slice(start)).not.toContain('/writeforest'); expect(requests.slice(start)).not.toContain('/writetimer')
  start=requests.length; await drag(page,card(page,'结果拖拽'),head(item(page,'右')),'inside',false); expect(requests.slice(start).filter(x=>x.startsWith('/write'))).toEqual([])
  for(const name of ['环甲','环乙']) await named(page,area(page,'待办').getByRole('button',{name:'新增闭环',exact:true}),name)
  const loops=area(page,'待办').locator('.loop')
  await record(page,loops.nth(0).getByRole('button',{name:'在闭环下新增待办',exact:true}),'待办拖拽','耗时:2s',4)
  const targetTag=await loops.nth(1).getAttribute('data-loop')
  start=requests.length; await drag(page,card(page,'待办拖拽'),head(loops.nth(1)))
  expect((await currentEvents(request)).find(x=>x.user.event==='待办拖拽').meta).toContainEqual({kind:'闭环',text:`闭环#${targetTag}|环乙`})
  expect(requests.slice(start)).not.toContain('/writeforest')
  start=requests.length; await drag(page,head(loops.nth(1)),head(loops.nth(0)),'before')
  expect(requests.slice(start)).toContain('/writeforest'); expect(requests.slice(start)).not.toContain('/writeevent')
  await page.reload(); await expect(loops.nth(0)).toHaveAttribute('data-loop',targetTag)
  start=requests.length; await drag(page,card(page,'待办拖拽'),head(item(page,'左')),'inside',false)
  await drag(page,card(page,'结果拖拽'),head(loops.nth(0)),'inside',false)
  expect(requests.slice(start).filter(x=>x.startsWith('/write'))).toEqual([])
  await page.screenshot({path:testInfo.outputPath('drag-layout.png'),fullPage:true})
})

test('归档单条与整组投送结果，保留闭环身份且不影响其他区域',async ({page,request}) => {
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'归属')
  const tag='闭环#11111111111111111111111111111111|相同闭环'
  await request.post('/writeevent',{data:[['归档','归档甲'],['归档','归档乙'],['归档','归档丙'],['待办','仍在待办'],['运行','仍在运行']].map(([region,text])=>({system:{source_id:null,deleted:false},user:{event:text},meta:[{kind:'业务区域',text:region},{kind:'闭环',text:tag},{kind:'属性',text:'评分:4'},{kind:'属性',text:'耗时:3s'}]}))})
  await page.reload(); await expect(page.locator('#message')).toHaveText('已读取')
  await page.getByRole('combobox',{name:'归档日期范围'}).selectOption('all'); await expect(page.locator('#message')).toHaveText('已读取')
  await page.getByRole('combobox',{name:'结果日期范围'}).selectOption('all'); await expect(page.locator('#message')).toHaveText('已读取')
  const before=await currentEvents(request), start=requests.length
  await drag(page,card(page,'归档甲'),head(item(page,'归属')))
  await expect(card(page,'归档甲').locator('.event-loop')).toHaveText('相同闭环')
  expect(requests.slice(start)).not.toContain('/writeforest')
  const batches=[]; page.on('request',r=>{if(new URL(r.url()).pathname==='/writeevent') batches.push(r.postDataJSON())})
  await drag(page,head(area(page,'归档').locator('.loop')),head(item(page,'归属')))
  expect(batches).toHaveLength(1); expect(batches[0]).toHaveLength(2)
  await expect(area(page,'归档').locator('.event')).toHaveCount(0)
  await expect(item(page,'归属').locator('.event')).toHaveCount(3)
  await expect(area(page,'结果').locator('.loop')).toHaveCount(0)
  const saved=await currentEvents(request)
  for(const original of before) {
    const current=saved.find(x=>x.system.source_id===original.system.source_id)
    expect(current.meta).toContainEqual({kind:'闭环',text:tag})
    expect(current.meta).toContainEqual({kind:'属性',text:'耗时:3s'})
    if(original.user.event.startsWith('仍在')) expect(current).toEqual(original)
    else expect(current.meta).toContainEqual({kind:'业务区域',text:'结果'})
  }
  expect(await area(page,'结果').innerText()).not.toContain('11111111111111111111111111111111')
  const boundary=requests.length
  await drag(page,card(page,'仍在待办'),head(area(page,'运行').locator('.loop')),'inside',false)
  await drag(page,head(area(page,'运行').locator('.loop')),head(area(page,'待办').locator('.loop')),'before',false)
  expect(requests.slice(boundary).filter(x=>x.startsWith('/write'))).toEqual([])
  const second='闭环#22222222222222222222222222222222|另一运行组'
  await request.post('/writeevent',{data:[{system:{source_id:null,deleted:false},user:{event:'另一运行事实'},meta:[{kind:'业务区域',text:'运行'},{kind:'闭环',text:second}]}]})
  await page.reload(); await expect(page.locator('#message')).toHaveText('已读取')
  const inferred=area(page,'运行').locator('.loop'), lastId=await inferred.nth(1).getAttribute('data-loop'), reorder=requests.length
  await drag(page,head(inferred.nth(1)),head(inferred.nth(0)),'before')
  expect(requests.slice(reorder)).not.toContain('/writeevent'); expect(requests.slice(reorder)).toContain('/writeforest')
  await page.reload(); await expect(inferred.nth(0)).toHaveAttribute('data-loop',lastId)
})

test('拖拽写入失败不修改森林、不乐观迁移',async ({page}) => {
  for(const name of ['原','目标']) await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),name)
  await record(page,head(item(page,'原')).getByRole('button',{name:'记录一条',exact:true}),'保留原处')
  await page.route('**/writeevent',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'拖拽写入失败'})}))
  const start=requests.length
  // 真实鼠标拖拽；失败流程没有“已保存”。
  const source=head(item(page,'原')), target=head(item(page,'目标')), a=await source.boundingBox(), b=await target.boundingBox()
  await page.mouse.move(a.x+70,a.y+a.height/2); await page.mouse.down(); await page.mouse.move(a.x+85,a.y+a.height/2,{steps:5}); await page.mouse.move(b.x+70,b.y+b.height/2,{steps:12}); await page.mouse.move(b.x+71,b.y+b.height/2); await expect(target).toHaveClass(/drop-inside/); await page.mouse.up()
  await expect(page.locator('#message')).toHaveText('拖拽写入失败')
  await expect(item(page,'原').locator('.event')).toHaveCount(1); await expect(item(page,'目标').locator('.item')).toHaveCount(0)
  expect(requests.slice(start)).not.toContain('/writeforest')
})

test('结果归档独立日期集合查询，事项汇总与嵌套统计，无写入',async ({page,request},testInfo) => {
  expect(datesInRange('quarter','2024-02-29')).toHaveLength(91)
  expect(datesInRange('month','2024-02-29').at(-1)).toBe('2024-02-29')
  expect(datesInRange('week','2027-01-01')).toEqual(['2026-12-28','2026-12-29','2026-12-30','2026-12-31','2027-01-01','2027-01-02','2027-01-03'])
  await page.clock.setFixedTime(new Date('2026-05-13T04:00:00Z'))
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'积累')
  await named(page,head(item(page,'积累')).getByRole('button',{name:'新增子事项',exact:true}),'练习')
  const samples=[['2026-05-13',10,2],['2026-05-11',20,3],['2026-05-01',30,4],['2026-04-01',40,5],['2026-03-31',50,1],['2026-05-14',60,4],[null,70,null]]
  await request.post('/writeevent',{data:['结果','归档'].flatMap(region=>samples.map(([date,seconds,score],index)=>({system:{source_id:null,deleted:false},user:{event:`${region}记录${index}`},meta:[{kind:'业务区域',text:region},...(region==='结果'?[{kind:'复利事项',text:'积累'},...(index<2?[{kind:'复利事项',text:'练习'}]:[])]:[]),{kind:'属性',text:`耗时:${seconds}s`},...(date?[{kind:'属性',text:`日期:${date}`}]:[]),...(score?[{kind:'属性',text:`评分:${score}`}]:[])]})))})
  await page.reload(); await expect(page.locator('#message')).toHaveText('已读取')
  const unchanged=await memory(request), start=requests.length, batches=[]
  page.on('request',r=>{if(new URL(r.url()).pathname==='/readevent') batches.push(r.postDataJSON())})
  await expect(page.getByRole('heading',{name:'结果',exact:true})).toBeVisible(); await expect(page.getByRole('heading',{name:'小事',exact:true})).toBeVisible()
  await expect(page.getByLabel('结果日期范围')).toHaveValue('today'); await expect(page.getByLabel('归档日期范围')).toHaveValue('today')
  await expect(area(page,'结果').locator('.event')).toHaveCount(1); await expect(area(page,'归档').locator('.event')).toHaveCount(1)
  const totals=head(item(page,'积累')).getByLabel('事项总耗时总评分')
  const checks=[['today',1,'10秒','2分'],['week',3,'1分30秒','9分'],['month',4,'2分0秒','13分'],['quarter',5,'2分40秒','18分'],['all',7,'4分40秒','19分']]
  for(const [range,count,time,score] of checks) {
    await page.getByLabel('结果日期范围').selectOption(range)
    await expect(area(page,'结果').locator('.event')).toHaveCount(count)
    await expect(totals.locator('span').nth(0)).toHaveText(time); await expect(totals.locator('span').nth(1)).toHaveText(score)
    await expect(area(page,'归档').locator('.event')).toHaveCount(1)
    const batch=batches.at(-1), dated=batch.filter(tags=>tags.some(tag=>tag.kind==='属性'&&tag.text.startsWith('日期:')))
    expect(batch.every(tags=>tags.filter(tag=>tag.text.startsWith('日期:')).length<=1)).toBe(true)
    expect(dated.length).toBeGreaterThan(0)
    if(range==='all') expect(dated.every(tags=>tags.some(tag=>tag.kind==='业务区域'&&tag.text==='归档'))).toBe(true)
    else expect(dated.some(tags=>tags.some(tag=>tag.kind==='业务区域'&&tag.text==='结果'))).toBe(true)
  }
  await page.getByLabel('归档日期范围').selectOption('today'); await expect(area(page,'归档').locator('.event')).toHaveCount(1); await expect(area(page,'结果').locator('.event')).toHaveCount(7)
  await page.getByLabel('结果日期范围').selectOption('today'); await expect(area(page,'结果').locator('.event')).toHaveCount(1)
  await expect(head(item(page,'练习')).getByLabel('事项总耗时总评分')).toContainText('10秒')
  expect(requests.slice(start).filter(path=>path.startsWith('/write'))).toEqual([])
  expect(await memory(request)).toEqual(unchanged)
  await page.screenshot({path:testInfo.outputPath('date-ranges-desktop.png'),fullPage:true})
  await page.setViewportSize({width:390,height:844}); await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true); await page.screenshot({path:testInfo.outputPath('date-ranges-mobile.png'),fullPage:true})
})

test('闭环新增只录入正文，模板新增复用卡片且确认保存前不落库',async ({page,request}) => {
  await named(page,area(page,'待办').getByRole('button',{name:'新增闭环',exact:true}),'录入闭环')
  await area(page,'待办').locator('.loop').getByRole('button',{name:'在闭环下新增待办',exact:true}).click()
  await expect(dialog(page).locator('.capture-steps')).toHaveText('1 正文')
  await expect(dialog(page).locator('.score-card')).not.toBeVisible()
  await page.getByLabel('小事正文',{exact:true}).fill('直接保存的待办')
  await dialog(page).getByRole('button',{name:'保存',exact:true}).click(); await expect(card(page,'直接保存的待办')).toHaveCount(1); await expect(page.locator('dialog')).toHaveCount(0)
  expect((await currentEvents(request))[0].meta.some(tag=>tag.text.startsWith('评分:'))).toBe(false)
  await page.getByRole('button',{name:'选择或管理模板',exact:true}).click(); await dialog(page).getByRole('button',{name:'+ 增加模板',exact:true}).click(); await page.getByLabel('模板名称').fill('录入模板')
  const start=requests.length
  await dialog(page).getByRole('button',{name:'+ 增加模板事项',exact:true}).click(); await page.getByLabel('小事正文',{exact:true}).fill('取消的草稿'); await dialog(page).getByRole('button',{name:'关闭',exact:true}).click()
  await expect(dialog(page).locator('.draft-row')).toHaveCount(0)
  await templateRecord(page,'复用正文卡片')
  await expect(dialog(page).locator('.event-body')).toHaveText('复用正文卡片')
  expect(requests.slice(start).filter(path=>path.startsWith('/write'))).toEqual([])
  await dialog(page).getByRole('button',{name:'保存模板',exact:true}).click(); await expect(page.locator('#message')).toHaveText('已保存')
  const [template]=await (await request.post('/readlooptemplate',{data:null})).json(); expect(template.events).toHaveLength(1); expect(template.events[0].user.event).toBe('复用正文卡片')
})


test('森林折叠记忆：嵌套恢复、视图隔离、改名移动及保存失败重试', async ({page,request}) => {
  await named(page,page.getByRole('button',{name:'新增视图',exact:true}),'折叠视图甲')
  const view = await page.locator('#view-select').inputValue()
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'父事项')
  await named(page,head(item(page,'父事项')).getByRole('button',{name:'新增子事项',exact:true}),'子事项')
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'目标事项')
  const body = name => item(page,name).locator(':scope > .branch-content')
  await head(item(page,'子事项')).getByRole('button',{name:'收起',exact:true}).click()
  await expect(body('子事项')).toHaveJSProperty('hidden',true)
  await head(item(page,'父事项')).getByRole('button',{name:'收起',exact:true}).click()
  await expect(body('父事项')).toHaveJSProperty('hidden',true)
  await page.reload(); await expect(body('父事项')).toHaveJSProperty('hidden',true)
  await head(item(page,'父事项')).getByRole('button',{name:'展开',exact:true}).click()
  await expect(body('父事项')).toHaveJSProperty('hidden',false); await expect(body('子事项')).toHaveJSProperty('hidden',true)
  await named(page,head(item(page,'子事项')).getByRole('button',{name:'重命名事项',exact:true}),'改名子事项')
  await expect(body('改名子事项')).toHaveJSProperty('hidden',true)
  await drag(page,head(item(page,'改名子事项')),head(item(page,'目标事项')))
  await expect(item(page,'目标事项').locator('.item[data-item="改名子事项"]')).toHaveCount(1)
  await expect(body('改名子事项')).toHaveJSProperty('hidden',true)
  await named(page,page.getByRole('button',{name:'新增视图',exact:true}),'折叠视图乙')
  await named(page,area(page,'结果').getByRole('button',{name:'新增根事项',exact:true}),'改名子事项')
  await expect(body('改名子事项')).toHaveJSProperty('hidden',false)
  await page.locator('#view-select').selectOption(view); await expect(page.locator('#message')).toHaveText('已保存')
  await expect(body('改名子事项')).toHaveJSProperty('hidden',true)
  await page.route('**/writeforest',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'折叠保存失败'})}))
  await head(item(page,'改名子事项')).getByRole('button',{name:'展开',exact:true}).click()
  await expect(page.locator('#message')).toContainText('折叠保存失败'); await expect(body('改名子事项')).toHaveJSProperty('hidden',true)
  await page.unroute('**/writeforest')
  await head(item(page,'改名子事项')).getByRole('button',{name:'展开',exact:true}).click()
  await expect(body('改名子事项')).toHaveJSProperty('hidden',false)
  await page.reload(); await expect(body('改名子事项')).toHaveJSProperty('hidden',false)
  const memory = await (await request.post('/readforest',{data:{workspace:true,item_templates:null}})).json()
  const saved = memory.item_templates.find(record=>String(record.id)===view)
  expect(saved.forest.find(node=>node.tag.text==='目标事项').children[0].is_fold).toBe(false)
  await page.setViewportSize({width:390,height:844})
  await page.getByRole('navigation',{name:'手机分区'}).getByRole('button',{name:'结果',exact:true}).click()
  await head(item(page,'改名子事项')).getByRole('button',{name:'收起',exact:true}).click()
  await expect(body('改名子事项')).toHaveJSProperty('hidden',true); await page.reload()
  await page.getByRole('navigation',{name:'手机分区'}).getByRole('button',{name:'结果',exact:true}).click()
  await expect(body('改名子事项')).toHaveJSProperty('hidden',true)
})

test('推导闭环折叠登记森林、保持顺序并按区域独立恢复', async ({page,request}) => {
  const tag = text => ({kind:'闭环',text:`闭环#${text.repeat(32)}|推导${text}`})
  await request.post('/writeevent',{data:[['运行','a'],['运行','b'],['待办','b']].map(([region,id])=>({system:{source_id:null,deleted:false},user:{event:`${region}${id}`},meta:[{kind:'业务区域',text:region},tag(id)]}))})
  await page.reload(); await expect(area(page,'运行').locator('.loop')).toHaveCount(2)
  const names = () => area(page,'运行').locator('.loop-name').allTextContents()
  const before = await names(), loop = area(page,'运行').locator('.loop').filter({has:page.locator('.loop-name',{hasText:'推导b'})})
  await loop.locator('.loop-name').click(); await expect(head(loop)).toHaveAttribute('aria-expanded','false')
  expect(await names()).toEqual(before)
  await expect(head(area(page,'待办').locator('.loop'))).toHaveAttribute('aria-expanded','true')
  await page.reload(); await expect(head(loop)).toHaveAttribute('aria-expanded','false'); expect(await names()).toEqual(before)
  const memory = await (await request.post('/readforest',{data:{workspace:true}})).json()
  expect(memory.workspace.forest.find(node=>node.tag.text==='运行').children.find(node=>node.tag.text===tag('b').text).is_fold).toBe(true)
  await head(loop).focus(); await head(loop).press('Space'); await expect(head(loop)).toHaveAttribute('aria-expanded','true')
  await page.reload(); await expect(head(loop)).toHaveAttribute('aria-expanded','true')
})
