import {test, expect} from '@playwright/test'

const area = (page, name) => page.locator(`.area[data-area="${name}"]`)
const item = (page, name) => page.locator(`.item[data-item="${name}"]`)
const card = (page, text) => page.locator('.event').filter({has: page.locator('.event-body', {hasText: text})})
const loop = (parent, name) => parent.locator('.loop').filter({has: parent.page().locator('.group-head strong', {hasText: name})})

async function nameClick(page, target, text) {
  await target.click()
  await expect(page.locator('#action-dialog')).toBeVisible()
  await page.locator('#action-name').fill(text)
  await page.locator('#action-dialog').getByRole('button', {name: '确定', exact: true}).click()
  await expect(page.locator('#action-dialog')).not.toBeVisible()
  await expect(page.locator('#workspace button').first()).toBeEnabled()
}
async function confirmClick(page, target) {
  await target.click()
  await expect(page.locator('#action-dialog')).toBeVisible()
  await expect(page.locator('#action-name')).not.toBeVisible()
  await page.locator('#action-dialog').getByRole('button', {name: '确定', exact: true}).click()
  await expect(page.locator('#action-dialog')).not.toBeVisible()
  await expect(page.locator('#message')).toHaveText('已保存')
}
async function addTag(page, kind, text) {
  await page.getByRole('button', {name: '增加标签', exact: true}).click()
  const row = page.locator('.tag-row').last()
  await row.getByLabel('标签种类').selectOption(kind)
  await row.getByLabel('标签文本').fill(text)
}
async function saveEvent(page, text) {
  await page.locator('#event').fill(text)
  await page.getByRole('button', {name: '保存小事', exact: true}).click()
  await expect(page.locator('#editor')).not.toBeVisible()
}
async function dragTo(page, source, target) {
  const sourceClass=await source.getAttribute('class') ?? '',targetClass=await target.getAttribute('class') ?? ''
  const handle=sourceClass.split(' ').includes('event') ? source.locator('.event-body') : sourceClass.includes('group-head') ? source.locator('strong') : source
  const landing=targetClass.includes('group-head') ? target.locator('strong') : target
  await Promise.all([
    page.waitForResponse(response => new URL(response.url()).pathname === '/writeevent' && response.request().method() === 'POST'),
    (async () => {
      await handle.hover()
      await page.mouse.down()
      const box = await handle.boundingBox()
      await page.mouse.move(box.x+5,box.y+5,{steps:5})
      await landing.hover()
      await landing.hover()
      await page.mouse.up()
    })(),
  ])
  await expect(page.locator('#message')).toHaveText('已保存')
  await expect(page.locator('#refresh')).toBeEnabled()
}

test.beforeEach(async ({page, request}) => {
  // 内嵌浏览器可能不展示原生 JS 弹窗，所有操作必须使用页面 DOM。
  await page.addInitScript(() => {
    window.prompt = () => { throw new Error('禁止使用浏览器 prompt') }
    window.confirm = () => { throw new Error('禁止使用浏览器 confirm') }
    window.alert = () => { throw new Error('禁止使用浏览器 alert') }
  })
  // 清理隔离服务的当前数据，历史保留。
  const current = await (await request.post('/readevent', {data: [[]]})).json()
  if (current[0].length) await request.post('/writeevent', {data: current[0].map(event => ({
    system: {source_id: event.system.source_id, deleted: true}, user: event.user, meta: event.meta,
  }))})
  const memory = await (await request.post('/readforest',{data:{workspace:true,item_templates:null}})).json()
  await request.post('/writeforest',{data:{workspace:{item_template_id:null,forest:['结果','待办','运行','归档'].map(text => ({tag:{kind:'业务区域',text},children:[]}))},
    item_templates:memory.item_templates.map(value => ({id:value.id,deleted:true,name:value.name,forest:value.forest}))}})
  const templates = await (await request.post('/readlooptemplate',{data:null})).json()
  if (templates.length) await request.post('/writelooptemplate',{data:templates.map(value => ({id:value.id,deleted:true,events:value.events}))})
  await page.goto('/')
  await expect(page.locator('#message')).toHaveText('已读取')
})

test('加闭环直接打开页面表单，支持取消、回车创建和四区入口', async ({page}) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await area(page, '待办').getByRole('button', {name: '+闭环', exact: true}).click()
  await expect(page.locator('#action-dialog')).toBeVisible()
  await expect(page.locator('#action-name')).toBeFocused()
  await page.locator('#action-name').fill('取消创建')
  await page.locator('#action-dialog').getByRole('button', {name: '取消', exact: true}).click()
  await expect(page.locator('.loop')).toHaveCount(0)
  for (const name of ['结果', '待办', '运行', '归档']) {
    await area(page, name).getByRole('button', {name: '+闭环', exact: true}).first().click()
    await page.locator('#action-name').fill(`${name}闭环`)
    await page.locator('#action-name').press('Enter')
    await expect(loop(area(page, name), `${name}闭环`)).toHaveCount(1)
  }
  await area(page, '待办').getByRole('button', {name: '+闭环', exact: true}).first().click()
  await page.locator('#action-name').press('Escape')
  await expect(page.locator('#action-dialog')).not.toBeVisible()
  await expect(page.locator('.loop')).toHaveCount(4)
  expect(errors).toEqual([])
})

test('创建、运行、归档、属性编辑与删除使用概念接口', async ({page}) => {
  const errors = [], writes = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => {if (request.method() === 'POST') writes.push(new URL(request.url()).pathname)})
  await nameClick(page, area(page, '结果').getByRole('button', {name: '+复利事项', exact: true}), '运动')
  await nameClick(page, item(page, '运动').getByRole('button', {name: '+闭环', exact: true}), '训练')
  await loop(item(page, '运动'), '训练').getByRole('button', {name: '+小事', exact: true}).click()
  await addTag(page, '属性', '评分:4')
  await addTag(page, '属性', '耗时:1800s')
  await addTag(page, '属性', '备注:保持动作稳定')
  await saveEvent(page, '游泳训练')
  const source = await card(page, '游泳训练').getAttribute('data-source')
  const moveStart=writes.length
  await card(page, '游泳训练').getByRole('button', {name: '移入运行', exact: true}).click()
  await expect(area(page, '运行').locator('.event')).toHaveCount(1)
  await expect(area(page, '结果').locator('.event')).toHaveCount(0)
  expect([...new Set(writes.slice(moveStart))].sort()).toEqual(['/readevent','/readtimer','/writeevent'])
  await area(page, '运行').getByRole('button', {name: '归档', exact: true}).click()
  await expect(area(page, '归档').locator('.event')).toHaveCount(1)
  await card(page, '游泳训练').getByRole('button', {name: '编辑', exact: true}).click()
  // 根据真实表单值定位属性行，其他属性不参与改写。
  const rows = page.locator('.tag-row')
  for (let index = 0; index < await rows.count(); index++) {
    const input = rows.nth(index).getByLabel('标签文本')
    if (await input.inputValue() === '评分:4') await input.fill('评分:5')
  }
  await saveEvent(page, '游泳训练完成')
  await expect(card(page, '游泳训练完成')).toContainText('评分:5')
  await expect(card(page, '游泳训练完成')).toContainText('耗时:1800s')
  await expect(card(page, '游泳训练完成')).toContainText('备注:保持动作稳定')
  await expect(card(page, '游泳训练完成')).toHaveAttribute('data-source', source)
  await card(page, '游泳训练完成').getByRole('button', {name: '编辑', exact: true}).click()
  for (let index = 0; index < await rows.count(); index++) {
    if (await rows.nth(index).getByLabel('标签文本').inputValue() === '备注:保持动作稳定') {
      await rows.nth(index).getByRole('button', {name: '移除', exact: true}).click()
      break
    }
  }
  await addTag(page, '属性', '日期:2026-10-01')
  await saveEvent(page, '游泳训练完成')
  await expect(card(page, '游泳训练完成')).not.toContainText('备注:')
  await expect(card(page, '游泳训练完成')).toContainText('评分:5')
  await expect(card(page, '游泳训练完成')).toContainText('日期:2026-10-01')
  await confirmClick(page, card(page, '游泳训练完成').getByRole('button', {name: '删除', exact: true}))
  await expect(page.locator('.event')).toHaveCount(0)
  expect(errors).toEqual([])
  expect([...new Set(writes)].sort()).toEqual(['/readevent', '/readforest', '/readlooptemplate', '/readtimer', '/writeevent', '/writeforest'])
})

test('单条和整组拖拽保持其他标签；改名和跨区域组删除', async ({page}) => {
  await nameClick(page, area(page, '结果').getByRole('button', {name: '+复利事项', exact: true}), '学习')
  await nameClick(page, area(page, '待办').getByRole('button', {name: '+闭环', exact: true}), '阅读')
  const todoLoop = () => loop(area(page, '待办'), '阅读')
  await todoLoop().getByRole('button', {name: '+小事', exact: true}).click()
  await addTag(page, '属性', '评分:3')
  await saveEvent(page, '阅读甲')
  await todoLoop().getByRole('button', {name: '+小事', exact: true}).click()
  await saveEvent(page, '阅读乙')
  await dragTo(page, todoLoop().locator('.group-head'), area(page, '运行').locator('h2'))
  await expect(area(page, '运行').locator('.event')).toHaveCount(2)
  await dragTo(page, card(page, '阅读乙'), area(page, '归档').locator('h2'))
  await expect(area(page, '归档').locator('.event')).toHaveCount(1)
  await dragTo(page, loop(area(page, '运行'), '阅读').locator('.group-head'), item(page, '学习').locator('.group-head'))
  await expect(item(page, '学习').locator('.event')).toHaveCount(1)
  await expect(area(page, '归档').locator('.event')).toHaveCount(1)
  await expect(card(page, '阅读甲')).toContainText('评分:3')
  await nameClick(page, item(page, '学习').getByRole('button', {name: '改名事项', exact: true}), '读书')
  await expect(item(page, '读书').locator('.event')).toHaveCount(1)
  await nameClick(page, loop(item(page, '读书'), '阅读').getByRole('button', {name: '改名闭环', exact: true}), '阅读完成')
  await expect(loop(area(page, '归档'), '阅读完成').locator('.event')).toHaveCount(1)
  await confirmClick(page, loop(item(page, '读书'), '阅读完成').getByRole('button', {name: '删除闭环', exact: true}))
  await expect(page.locator('.event')).toHaveCount(0)
})

test('同名闭环独立、空组刷新保留、解除闭环及事项组拖拽删除', async ({page}) => {
  await nameClick(page, area(page, '结果').getByRole('button', {name: '+复利事项', exact: true}), '空事项')
  await nameClick(page, area(page, '待办').getByRole('button', {name: '+闭环', exact: true}), '空闭环')
  await page.reload()
  await expect(page.locator('#message')).toHaveText('已读取')
  await expect(page.locator('.item')).toHaveCount(1)
  await expect(page.locator('.loop')).toHaveCount(1)
  await confirmClick(page, item(page, '空事项').getByRole('button', {name:'删除事项',exact:true}))
  await confirmClick(page, loop(area(page,'待办'),'空闭环').getByRole('button',{name:'删除闭环',exact:true}))
  await nameClick(page, area(page, '待办').getByRole('button', {name: '+闭环', exact: true}), '每日整理')
  await area(page, '待办').locator('.loop').first().getByRole('button', {name: '+小事', exact: true}).click()
  await saveEvent(page, '第一组')
  await nameClick(page, area(page, '待办').getByRole('button', {name: '+闭环', exact: true}), '每日整理')
  await area(page, '待办').locator('.loop').last().getByRole('button', {name: '+小事', exact: true}).click()
  await saveEvent(page, '第二组')
  const groups = area(page, '待办').locator('.loop')
  expect(await groups.nth(0).getAttribute('data-loop')).not.toBe(await groups.nth(1).getAttribute('data-loop'))
  await page.reload()
  await expect(groups).toHaveCount(2)
  await dragTo(page, card(page, '第一组'), area(page, '待办').locator('.drop-none'))
  await expect(area(page, '待办').locator('.drop-none .event')).toHaveCount(1)
  await nameClick(page, area(page, '结果').getByRole('button', {name: '+复利事项', exact: true}), '整理')
  await dragTo(page, card(page, '第一组'), item(page, '整理').locator('.group-head'))
  await dragTo(page, item(page, '整理').locator('.group-head'), area(page, '运行').locator('h2'))
  await expect(area(page, '运行').locator('.event')).toHaveCount(1)
  await confirmClick(page, item(page, '整理').getByRole('button', {name: '删除事项', exact: true}))
  await expect(card(page, '第一组')).toHaveCount(0)
  await expect(card(page, '第二组')).toHaveCount(1)
  await area(page, '待办').getByRole('button', {name: '+小事', exact: true}).first().click()
  await saveEvent(page, '')
  await expect(page.locator('.event-body', {hasText: '（空正文）'})).toHaveCount(1)
})

test('协议拒绝错误属性，保留输入；窄屏无横向溢出', async ({page}, testInfo) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await area(page, '待办').getByRole('button', {name: '+小事', exact: true}).first().click()
  await page.locator('#event').fill('输入需要保留')
  await addTag(page, '属性', '评分:9')
  await page.getByRole('button', {name: '保存小事', exact: true}).click()
  await expect(page.locator('#message')).toContainText('格式不符合协议')
  await expect(page.locator('#editor-error')).toContainText('格式不符合协议')
  await expect(page.locator('#editor')).toBeVisible()
  await expect(page.locator('#event')).toHaveValue('输入需要保留')
  await page.locator('.tag-row').last().getByLabel('标签文本').fill('评分:4')
  await saveEvent(page, '输入需要保留')
  await page.screenshot({path: testInfo.outputPath('desktop.png'), fullPage: true})
  await page.setViewportSize({width: 390, height: 844})
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path: testInfo.outputPath('mobile.png'), fullPage: true})
  expect(errors).toEqual([])
})

test('空组改名删除、拖入其他闭环及重新归属复利事项', async ({page}) => {
  await nameClick(page, area(page, '结果').getByRole('button', {name: '+复利事项', exact: true}), '临时')
  await nameClick(page, item(page, '临时').getByRole('button', {name: '改名事项', exact: true}), '临时改名')
  await confirmClick(page, item(page, '临时改名').getByRole('button', {name: '删除事项', exact: true}))
  await expect(page.locator('.item')).toHaveCount(0)
  await nameClick(page, area(page, '待办').getByRole('button', {name: '+闭环', exact: true}), '空组')
  await nameClick(page, loop(area(page, '待办'), '空组').getByRole('button', {name: '改名闭环', exact: true}), '空组改名')
  await confirmClick(page, loop(area(page, '待办'), '空组改名').getByRole('button', {name: '删除闭环', exact: true}))
  await expect(page.locator('.loop')).toHaveCount(0)
  await nameClick(page, area(page, '待办').getByRole('button', {name: '+闭环', exact: true}), '甲组')
  await loop(area(page, '待办'), '甲组').getByRole('button', {name: '+小事', exact: true}).click()
  await saveEvent(page, '转换分组')
  await nameClick(page, area(page, '归档').getByRole('button', {name: '+闭环', exact: true}), '乙组')
  await dragTo(page, card(page, '转换分组'), loop(area(page, '归档'), '乙组').locator('.group-head'))
  await expect(loop(area(page, '归档'), '乙组').locator('.event')).toHaveCount(1)
  await nameClick(page, area(page, '结果').getByRole('button', {name: '+复利事项', exact: true}), '方向甲')
  await nameClick(page, area(page, '结果').getByRole('button', {name: '+复利事项', exact: true}), '方向乙')
  await dragTo(page, card(page, '转换分组'), item(page, '方向甲').locator('.group-head'))
  await dragTo(page, card(page, '转换分组'), item(page, '方向乙').locator('.group-head'))
  await expect(item(page, '方向甲').locator('.event')).toHaveCount(0)
  await expect(item(page, '方向乙').locator('.event')).toHaveCount(1)
  await expect(card(page, '转换分组')).toContainText('闭环：乙组')
  await confirmClick(page, item(page, '方向乙').getByRole('button', {name: '删除事项', exact: true}))
  await expect(page.locator('.event')).toHaveCount(0)
})


test('嵌套树、视图切换、同步双写与层级拖拽', async ({page},testInfo) => {
  const errors=[], requests=[]
  page.on('pageerror',error => errors.push(error.message))
  page.on('request',request => {if(request.method()==='POST') requests.push({path:new URL(request.url()).pathname,body:request.postDataJSON()})})
  await nameClick(page,page.locator('#new-view'),'学习视图')
  await expect(page.locator('#view-select option:checked')).toHaveText('学习视图')
  const viewA=await page.locator('#view-select').inputValue()
  await nameClick(page,area(page,'结果').getByRole('button',{name:'+复利事项',exact:true}),'学习')
  await nameClick(page,item(page,'学习').getByRole('button',{name:'+子事项',exact:true}),'阅读')
  await item(page,'阅读').getByRole('button',{name:'+小事',exact:true}).click()
  await saveEvent(page,'读完一章')
  await expect(item(page,'阅读').locator('.event')).toHaveCount(1)
  await expect(card(page,'读完一章')).toContainText('复利事项：学习')
  await expect(card(page,'读完一章')).toContainText('复利事项：阅读')
  await nameClick(page,item(page,'阅读').getByRole('button',{name:'+子事项',exact:true}),'精读')
  const dual=requests.filter(value => value.path==='/writeforest' && value.body.workspace && value.body.item_templates)
  expect(dual.length).toBeGreaterThan(0)
  await page.locator('#view-select').selectOption('')
  await expect(page.locator('.item')).toHaveCount(0)
  // 视图不显示的 event 仍显示在区域根，避免把查询结构当成归属实体。
  await expect(card(page,'读完一章')).toHaveCount(1)
  await nameClick(page,page.locator('#new-view'),'运动视图')
  await expect(page.locator('#view-select option:checked')).toHaveText('运动视图')
  await expect(page.locator('.item')).toHaveCount(0)
  await nameClick(page,area(page,'结果').getByRole('button',{name:'+复利事项',exact:true}),'运动')
  await page.locator('#view-select').selectOption(viewA)
  await expect(item(page,'精读')).toHaveCount(1)
  await expect(item(page,'运动')).toHaveCount(0)
  await page.screenshot({path:testInfo.outputPath('tree-desktop.png'),fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path:testInfo.outputPath('tree-mobile.png'),fullPage:true})
  await page.setViewportSize({width:1440,height:900})
  await page.reload();await expect(page.locator('#message')).toHaveText('已读取')
  await expect(page.locator('#view-select')).toHaveValue(viewA)
  await expect(item(page,'阅读').locator('.event')).toHaveCount(1)
  await item(page,'阅读').locator(':scope > .group-head').getByRole('button',{name:'提升',exact:true}).click()
  await expect(area(page,'结果').locator(':scope > .item')).toHaveCount(2)
  await expect(card(page,'读完一章')).not.toContainText('复利事项：学习')
  await dragTo(page,item(page,'阅读').locator(':scope > .group-head'),item(page,'学习').locator(':scope > .group-head'))
  await expect(item(page,'学习').locator('.item[data-item="阅读"]')).toHaveCount(1)
  await expect(card(page,'读完一章')).toContainText('复利事项：学习')
  await nameClick(page,page.locator('#rename-view'),'阅读视图')
  await expect(page.locator('#view-select option:checked')).toHaveText('阅读视图')
  await confirmClick(page,page.locator('#delete-view'))
  await expect(card(page,'读完一章')).toHaveCount(1)
  expect(errors).toEqual([])
  const allowed=['/writeevent','/readevent','/writeforest','/readforest','/writelooptemplate','/readlooptemplate','/writetimer','/readtimer']
  expect(requests.every(value => allowed.includes(value.path))).toBe(true)
})

test('闭环模板数组编辑、刷新恢复、重复实例化与删除',async ({page}) => {
  const errors=[];page.on('pageerror',error => errors.push(error.message))
  await page.locator('summary').click()
  await page.locator('#new-loop-template').click()
  await page.locator('#template-name').fill('每日阅读')
  await page.getByLabel('模板小事正文').fill('阅读十页')
  await page.locator('#add-draft').click()
  await page.getByLabel('模板小事正文').last().fill('写总结')
  await page.getByRole('button',{name:'保存模板',exact:true}).click()
  await expect(page.locator('#template-dialog')).not.toBeVisible()
  await page.locator('#loop-templates').getByRole('button',{name:'编辑模板',exact:true}).click()
  await page.locator('#template-name').fill('每日精读')
  await page.getByLabel('模板小事正文').last().fill('写一句总结')
  await page.locator('#add-draft').click()
  await page.getByLabel('模板小事正文').last().fill('临时条目')
  await page.locator('#template-events .actions').last().getByRole('button',{name:'移除小事',exact:true}).click()
  await page.getByRole('button',{name:'保存模板',exact:true}).click()
  await expect(page.locator('#template-dialog')).not.toBeVisible()
  await page.reload();await expect(page.locator('#message')).toHaveText('已读取')
  await page.locator('summary').click()
  await expect(page.locator('#loop-templates')).toContainText('每日精读')
  await page.locator('#loop-templates').getByRole('button',{name:'使用模板',exact:true}).click()
  await expect(area(page,'待办').locator('.event')).toHaveCount(2)
  await page.locator('#loop-templates').getByRole('button',{name:'使用模板',exact:true}).click()
  await expect(area(page,'待办').locator('.event')).toHaveCount(4)
  const groups=area(page,'待办').locator('.loop')
  await expect(groups).toHaveCount(2)
  expect(await groups.nth(0).getAttribute('data-loop')).not.toBe(await groups.nth(1).getAttribute('data-loop'))
  await confirmClick(page,page.locator('#loop-templates').getByRole('button',{name:'删除模板',exact:true}))
  await expect(page.locator('#loop-templates > div')).toHaveCount(0)
  await expect(page.locator('.event')).toHaveCount(4)
  expect(errors).toEqual([])
})


test('内联计时运行暂停继续不写event，结束写耗时并重置；绑定源ID且不轮询',async ({page,request},testInfo) => {
  const errors=[],calls=[]
  page.on('pageerror',error => errors.push(error.message))
  page.on('request',request => {if(request.method()==='POST') calls.push({path:new URL(request.url()).pathname,body:request.postDataJSON()})})
  await area(page,'待办').getByRole('button',{name:'+小事',exact:true}).first().click()
  await addTag(page,'属性','评分:4');await addTag(page,'属性','耗时:2s')
  await saveEvent(page,'计时验证')
  const source=await card(page,'计时验证').getAttribute('data-source')
  const before=await (await request.post('/readevent',{data:[[]]})).json()
  const startIndex=calls.length
  await card(page,'计时验证').getByRole('button',{name:'运行',exact:true}).click()
  await expect(card(page,'计时验证').getByRole('button',{name:'暂停',exact:true})).toBeVisible()
  await expect(area(page,'待办').locator('.event')).toHaveCount(1)
  const display=card(page,'计时验证').locator('.timer-display')
  await expect(display).not.toHaveText('00:00:00',{timeout:4000})
  expect(calls.slice(startIndex).map(value => value.path)).toEqual(['/writetimer'])
  await page.screenshot({path:testInfo.outputPath('timer-desktop.png'),fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path:testInfo.outputPath('timer-mobile.png'),fullPage:true})
  await page.setViewportSize({width:1440,height:900})
  await card(page,'计时验证').getByRole('button',{name:'暂停',exact:true}).click()
  await expect(card(page,'计时验证').getByRole('button',{name:'继续',exact:true})).toBeVisible()
  const paused=await display.textContent()
  await page.reload();await expect(page.locator('#message')).toHaveText('已读取')
  await expect(card(page,'计时验证').locator('.timer-display')).toHaveText(paused)
  await card(page,'计时验证').getByRole('button',{name:'继续',exact:true}).click()
  await expect(card(page,'计时验证').getByRole('button',{name:'暂停',exact:true})).toBeVisible()
  expect(await (await request.post('/readevent',{data:[[]]})).json()).toEqual(before)
  await card(page,'计时验证').getByRole('button',{name:'编辑',exact:true}).click()
  await saveEvent(page,'计时验证修订')
  await expect(card(page,'计时验证修订').getByRole('button',{name:'暂停',exact:true})).toBeVisible()
  await card(page,'计时验证修订').getByRole('button',{name:'移入运行',exact:true}).click()
  await expect(area(page,'运行').locator('.event')).toHaveCount(1)
  await expect(card(page,'计时验证修订').getByRole('button',{name:'暂停',exact:true})).toBeVisible()
  const beforeEnd=await (await request.post('/readevent',{data:[[]]})).json()
  const finishIndex=calls.length
  await card(page,'计时验证修订').getByRole('button',{name:'结束',exact:true}).click()
  await expect(card(page,'计时验证修订').getByRole('button',{name:'运行',exact:true})).toBeVisible()
  await expect(card(page,'计时验证修订').locator('.timer-display')).toHaveCount(0)
  await expect(card(page,'计时验证修订')).toContainText('评分:4')
  const final=await (await request.post('/readevent',{data:[[]]})).json()
  expect(final[0][0].system.source_id).toBe(Number(source))
  expect(final[0][0].system.version_id).toBe(beforeEnd[0][0].system.version_id+1)
  expect(Number(final[0][0].meta.find(tag => tag.text.startsWith('耗时:')).text.slice(3,-1))).toBeGreaterThan(2)
  const ending=calls.slice(finishIndex).filter(value => value.path.startsWith('/write'))
  expect(ending.map(value => value.path)).toEqual(['/writetimer','/writeevent','/writetimer'])
  expect(ending[0].body).toEqual({key:source,state:'paused'})
  expect(ending[2].body).toEqual({key:source,state:'reset'})
  expect(calls.filter(value => value.path==='/writetimer').every(value => value.body.key===source)).toBe(true)
  // 运行、暂停、继续直到主动编辑前，event 版本没有变化。
  expect(calls.slice(startIndex).filter(value => value.path==='/writeevent')).toHaveLength(3)
  expect(before[0][0].system.source_id).toBe(Number(source))
  expect(errors).toEqual([])
})

test('结束写event失败保留暂停耗时，重试成功后才reset',async ({page,request}) => {
  await area(page,'待办').getByRole('button',{name:'+小事',exact:true}).first().click();await saveEvent(page,'结束失败验证')
  const source=await card(page,'结束失败验证').getAttribute('data-source')
  await card(page,'结束失败验证').getByRole('button',{name:'运行',exact:true}).click()
  await expect(card(page,'结束失败验证').locator('.timer-display')).not.toHaveText('00:00:00',{timeout:4000})
  await page.route('**/writeevent',route => route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'测试写入失败'})}))
  await card(page,'结束失败验证').getByRole('button',{name:'结束',exact:true}).click()
  await expect(page.locator('#message')).toHaveText('测试写入失败')
  await expect(card(page,'结束失败验证').getByRole('button',{name:'继续',exact:true})).toBeVisible()
  const timer=await (await request.post('/readtimer',{data:[source]})).json()
  expect(timer[0].state).toBe('paused');expect(timer[0].elapsed_ms).toBeGreaterThan(0)
  await page.unroute('**/writeevent')
  await card(page,'结束失败验证').getByRole('button',{name:'结束',exact:true}).click()
  await expect(card(page,'结束失败验证').getByRole('button',{name:'运行',exact:true})).toBeVisible()
  const reset=await (await request.post('/readtimer',{data:[source]})).json()
  expect(reset[0]).toEqual({key:source,state:'paused',elapsed_ms:0})
})
